#!/bin/bash
# Quick Test Script for RDS Operations Dashboard
# Generated by: claude-3.5-sonnet

set -e

echo "========================================="
echo "RDS Dashboard Quick Test"
echo "========================================="
echo ""

# Colors for output
GREEN='\033[0.32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Test counter
TESTS_PASSED=0
TESTS_FAILED=0

# Function to print test result
test_result() {
    if [ $1 -eq 0 ]; then
        echo -e "${GREEN}✓ PASS${NC}: $2"
        ((TESTS_PASSED++))
    else
        echo -e "${RED}✗ FAIL${NC}: $2"
        ((TESTS_FAILED++))
    fi
}

echo "1. Testing Python Syntax..."
echo "-------------------------------------------"

# Test discovery handler
python3 -m py_compile lambda/discovery/handler.py 2>/dev/null
test_result $? "Discovery handler syntax"

# Test discovery persistence
python3 -m py_compile lambda/discovery/persistence.py 2>/dev/null
test_result $? "Discovery persistence syntax"

# Test discovery monitoring
python3 -m py_compile lambda/discovery/monitoring.py 2>/dev/null
test_result $? "Discovery monitoring syntax"

# Test health monitor handler
python3 -m py_compile lambda/health-monitor/handler.py 2>/dev/null
test_result $? "Health monitor handler syntax"

# Test cache manager
python3 -m py_compile lambda/health-monitor/cache_manager.py 2>/dev/null
test_result $? "Cache manager syntax"

# Test shared modules
python3 -m py_compile lambda/shared/aws_clients.py 2>/dev/null
test_result $? "AWS clients module syntax"

python3 -m py_compile lambda/shared/logger.py 2>/dev/null
test_result $? "Logger module syntax"

python3 -m py_compile lambda/shared/config.py 2>/dev/null
test_result $? "Config module syntax"

python3 -m py_compile lambda/shared/config_file_loader.py 2>/dev/null
test_result $? "Config file loader syntax"

echo ""
echo "2. Testing Configuration..."
echo "-------------------------------------------"

# Test config file exists
if [ -f "config/dashboard-config.json" ]; then
    test_result 0 "Config file exists"
    
    # Test JSON validity
    python3 -c "import json; json.load(open('config/dashboard-config.json'))" 2>/dev/null
    test_result $? "Config JSON is valid"
else
    test_result 1 "Config file exists"
fi

echo ""
echo "3. Testing TypeScript/CDK..."
echo "-------------------------------------------"

cd infrastructure

# Test if node_modules exists
if [ -d "node_modules" ]; then
    test_result 0 "Node modules installed"
else
    echo -e "${YELLOW}⚠ WARNING${NC}: Node modules not installed. Run 'npm install' in infrastructure/"
    test_result 1 "Node modules installed"
fi

# Test TypeScript compilation
if command -v tsc &> /dev/null; then
    tsc --noEmit 2>/dev/null
    test_result $? "TypeScript compilation"
else
    echo -e "${YELLOW}⚠ WARNING${NC}: TypeScript not installed"
    test_result 1 "TypeScript compilation"
fi

cd ..

echo ""
echo "4. Testing AWS CLI Configuration..."
echo "-------------------------------------------"

# Test AWS CLI
if command -v aws &> /dev/null; then
    test_result 0 "AWS CLI installed"
    
    # Test AWS credentials
    aws sts get-caller-identity &>/dev/null
    test_result $? "AWS credentials configured"
else
    test_result 1 "AWS CLI installed"
fi

echo ""
echo "5. Testing Python Dependencies..."
echo "-------------------------------------------"

# Test boto3
python3 -c "import boto3" 2>/dev/null
test_result $? "boto3 installed"

# Test botocore
python3 -c "import botocore" 2>/dev/null
test_result $? "botocore installed"

echo ""
echo "========================================="
echo "Test Summary"
echo "========================================="
echo -e "${GREEN}Passed: $TESTS_PASSED${NC}"
echo -e "${RED}Failed: $TESTS_FAILED${NC}"
echo ""

if [ $TESTS_FAILED -eq 0 ]; then
    echo -e "${GREEN}✓ All tests passed!${NC}"
    echo ""
    echo "Next steps:"
    echo "1. Update config/dashboard-config.json with your AWS account IDs"
    echo "2. Run: cd infrastructure && npm install"
    echo "3. Run: cdk bootstrap"
    echo "4. Run: cdk deploy --all"
    exit 0
else
    echo -e "${RED}✗ Some tests failed. Please fix the issues above.${NC}"
    exit 1
fi
