# Quick Test Script for RDS Operations Dashboard (PowerShell)
# Generated by: claude-3.5-sonnet

Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "RDS Dashboard Quick Test" -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host ""

# Test counters
$script:TestsPassed = 0
$script:TestsFailed = 0

# Function to print test result
function Test-Result {
    param(
        [bool]$Success,
        [string]$TestName
    )
    
    if ($Success) {
        Write-Host "PASS: $TestName" -ForegroundColor Green
        $script:TestsPassed++
    }
    else {
        Write-Host "FAIL: $TestName" -ForegroundColor Red
        $script:TestsFailed++
    }
}

Write-Host "1. Testing Python Syntax..." -ForegroundColor Yellow
Write-Host "-------------------------------------------"

# Test discovery handler
try {
    python -m py_compile lambda/discovery/handler.py 2>$null
    Test-Result -Success $true -TestName "Discovery handler syntax"
} catch {
    Test-Result -Success $false -TestName "Discovery handler syntax"
}

# Test discovery persistence
try {
    python -m py_compile lambda/discovery/persistence.py 2>$null
    Test-Result -Success $true -TestName "Discovery persistence syntax"
} catch {
    Test-Result -Success $false -TestName "Discovery persistence syntax"
}

# Test discovery monitoring
try {
    python -m py_compile lambda/discovery/monitoring.py 2>$null
    Test-Result -Success $true -TestName "Discovery monitoring syntax"
} catch {
    Test-Result -Success $false -TestName "Discovery monitoring syntax"
}

# Test health monitor handler
try {
    python -m py_compile lambda/health-monitor/handler.py 2>$null
    Test-Result -Success $true -TestName "Health monitor handler syntax"
} catch {
    Test-Result -Success $false -TestName "Health monitor handler syntax"
}

# Test cache manager
try {
    python -m py_compile lambda/health-monitor/cache_manager.py 2>$null
    Test-Result -Success $true -TestName "Cache manager syntax"
} catch {
    Test-Result -Success $false -TestName "Cache manager syntax"
}

# Test shared modules
try {
    python -m py_compile lambda/shared/aws_clients.py 2>$null
    Test-Result -Success $true -TestName "AWS clients module syntax"
} catch {
    Test-Result -Success $false -TestName "AWS clients module syntax"
}

try {
    python -m py_compile lambda/shared/logger.py 2>$null
    Test-Result -Success $true -TestName "Logger module syntax"
} catch {
    Test-Result -Success $false -TestName "Logger module syntax"
}

try {
    python -m py_compile lambda/shared/config.py 2>$null
    Test-Result -Success $true -TestName "Config module syntax"
} catch {
    Test-Result -Success $false -TestName "Config module syntax"
}

try {
    python -m py_compile lambda/shared/config_file_loader.py 2>$null
    Test-Result -Success $true -TestName "Config file loader syntax"
} catch {
    Test-Result -Success $false -TestName "Config file loader syntax"
}

Write-Host ""
Write-Host "2. Testing Configuration..." -ForegroundColor Yellow
Write-Host "-------------------------------------------"

# Test config file exists
if (Test-Path "config/dashboard-config.json") {
    Test-Result -Success $true -TestName "Config file exists"
    
    # Test JSON validity
    try {
        $config = Get-Content "config/dashboard-config.json" | ConvertFrom-Json
        Test-Result -Success $true -TestName "Config JSON is valid"
    } catch {
        Test-Result -Success $false -TestName "Config JSON is valid"
    }
} else {
    Test-Result -Success $false -TestName "Config file exists"
}

Write-Host ""
Write-Host "3. Testing TypeScript/CDK..." -ForegroundColor Yellow
Write-Host "-------------------------------------------"

Push-Location infrastructure

# Test if node_modules exists
if (Test-Path "node_modules") {
    Test-Result -Success $true -TestName "Node modules installed"
} else {
    Write-Host "⚠ WARNING: Node modules not installed. Run 'npm install' in infrastructure/" -ForegroundColor Yellow
    Test-Result -Success $false -TestName "Node modules installed"
}

# Test TypeScript compilation
if (Get-Command tsc -ErrorAction SilentlyContinue) {
    try {
        tsc --noEmit 2>$null
        Test-Result -Success $true -TestName "TypeScript compilation"
    } catch {
        Test-Result -Success $false -TestName "TypeScript compilation"
    }
} else {
    Write-Host "⚠ WARNING: TypeScript not installed" -ForegroundColor Yellow
    Test-Result -Success $false -TestName "TypeScript compilation"
}

Pop-Location

Write-Host ""
Write-Host "4. Testing AWS CLI Configuration..." -ForegroundColor Yellow
Write-Host "-------------------------------------------"

# Test AWS CLI
if (Get-Command aws -ErrorAction SilentlyContinue) {
    Test-Result -Success $true -TestName "AWS CLI installed"
    
    # Test AWS credentials
    try {
        aws sts get-caller-identity 2>$null | Out-Null
        Test-Result -Success $true -TestName "AWS credentials configured"
    } catch {
        Test-Result -Success $false -TestName "AWS credentials configured"
    }
} else {
    Test-Result -Success $false -TestName "AWS CLI installed"
}

Write-Host ""
Write-Host "5. Testing Python Dependencies..." -ForegroundColor Yellow
Write-Host "-------------------------------------------"

# Test boto3
try {
    python -c "import boto3" 2>$null
    Test-Result -Success $true -TestName "boto3 installed"
} catch {
    Test-Result -Success $false -TestName "boto3 installed"
}

# Test botocore
try {
    python -c "import botocore" 2>$null
    Test-Result -Success $true -TestName "botocore installed"
} catch {
    Test-Result -Success $false -TestName "botocore installed"
}

Write-Host ""
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "Test Summary" -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "Passed: $TestsPassed" -ForegroundColor Green
Write-Host "Failed: $TestsFailed" -ForegroundColor Red
Write-Host ""

if ($TestsFailed -eq 0) {
    Write-Host "All tests passed!" -ForegroundColor Green
    Write-Host ""
    Write-Host "Next steps:"
    Write-Host "1. Update config/dashboard-config.json with your AWS account IDs"
    Write-Host "2. Run: cd infrastructure; npm install"
    Write-Host "3. Run: cdk bootstrap"
    Write-Host "4. Run: cdk deploy --all"
    exit 0
}
else {
    Write-Host "Some tests failed. Please fix the issues above." -ForegroundColor Red
    exit 1
}
