"""
Account Onboarding Module

Generated by: claude-3.5-sonnet
Timestamp: 2025-12-08T00:00:00Z
Version: 1.0.0
Policy Version: v1.0.0
"""

from .external_id_manager import ExternalIdManager

__all__ = ['ExternalIdManager']
