"""
External ID Manager for Account Onboarding

Generated by: claude-3.5-sonnet
Timestamp: 2025-12-08T00:00:00Z
Version: 1.0.0
Policy Version: v1.0.0
Traceability: REQ-9.1, REQ-9.2, REQ-9.4 → DESIGN-001 → TASK-1.4
Review Status: Pending
Risk Level: Level 2

Purpose: Manage external IDs for cross-account roles including generation,
encryption, storage in Secrets Manager, and retrieval.

Design Decisions:
- External IDs are 32-character alphanumeric strings
- Stored in Secrets Manager with pattern: rds-dashboard/external-ids/{account_id}
- Encrypted using KMS key dedicated to external ID encryption
- Cached in Lambda memory for 5 minutes to reduce API calls
"""

import json
import secrets
import string
import time
from typing import Dict, Optional
from datetime import datetime

import boto3
from botocore.exceptions import ClientError


class ExternalIdManager:
    """Manages external IDs for cross-account roles"""
    
    # Secret naming pattern
    SECRET_NAME_PATTERN = "rds-dashboard/external-ids/{account_id}"
    
    # External ID format
    EXTERNAL_ID_LENGTH = 32
    EXTERNAL_ID_CHARS = string.ascii_letters + string.digits
    
    # Cache TTL (5 minutes)
    CACHE_TTL_SECONDS = 300
    
    def __init__(self, kms_key_id: str):
        """
        Initialize External ID Manager
        
        Args:
            kms_key_id: KMS key ID for encrypting external IDs
        """
        self.kms_key_id = kms_key_id
        self.secrets_client = boto3.client('secretsmanager')
        self.kms_client = boto3.client('kms')
        
        # In-memory cache: {account_id: (external_id, expiry_timestamp)}
        self._cache: Dict[str, tuple[str, float]] = {}
    
    def generate_external_id(self) -> str:
        """
        Generate a cryptographically secure random external ID
        
        Returns:
            32-character alphanumeric string
            
        Validates: Property 38 (External ID Format and Uniqueness)
        """
        return ''.join(
            secrets.choice(self.EXTERNAL_ID_CHARS)
            for _ in range(self.EXTERNAL_ID_LENGTH)
        )
    
    def create_external_id(self, account_id: str) -> str:
        """
        Generate and store a new external ID for an account
        
        Args:
            account_id: AWS account ID (12 digits)
            
        Returns:
            Generated external ID
            
        Raises:
            ValueError: If account_id format is invalid
            ClientError: If Secrets Manager operation fails
            
        Requirements: REQ-9.1, REQ-9.2
        """
        # Validate account ID format
        if not account_id.isdigit() or len(account_id) != 12:
            raise ValueError(f"Invalid account ID format: {account_id}")
        
        # Generate external ID
        external_id = self.generate_external_id()
        
        # Prepare secret value
        secret_value = {
            "external_id": external_id,
            "created_at": datetime.utcnow().isoformat() + "Z",
            "account_id": account_id,
            "rotation_enabled": True,
            "last_rotated": None
        }
        
        # Store in Secrets Manager
        secret_name = self.SECRET_NAME_PATTERN.format(account_id=account_id)
        
        try:
            self.secrets_client.create_secret(
                Name=secret_name,
                Description=f"External ID for cross-account role in account {account_id}",
                SecretString=json.dumps(secret_value),
                KmsKeyId=self.kms_key_id,
                Tags=[
                    {'Key': 'Project', 'Value': 'RDSDashboard'},
                    {'Key': 'Feature', 'Value': 'AutomatedOnboarding'},
                    {'Key': 'AccountId', 'Value': account_id},
                ]
            )
        except ClientError as e:
            if e.response['Error']['Code'] == 'ResourceExistsException':
                # Secret already exists, retrieve it instead
                return self.get_external_id(account_id)
            raise
        
        # Cache the external ID
        self._cache[account_id] = (external_id, time.time() + self.CACHE_TTL_SECONDS)
        
        return external_id
    
    def get_external_id(self, account_id: str) -> str:
        """
        Retrieve external ID for an account
        
        Args:
            account_id: AWS account ID (12 digits)
            
        Returns:
            External ID for the account
            
        Raises:
            ValueError: If account_id format is invalid
            ClientError: If secret not found or retrieval fails
            
        Requirements: REQ-9.4
        Validates: Property 41 (External ID Round-Trip Consistency)
        """
        # Validate account ID format
        if not account_id.isdigit() or len(account_id) != 12:
            raise ValueError(f"Invalid account ID format: {account_id}")
        
        # Check cache first
        if account_id in self._cache:
            external_id, expiry = self._cache[account_id]
            if time.time() < expiry:
                return external_id
            else:
                # Cache expired, remove entry
                del self._cache[account_id]
        
        # Retrieve from Secrets Manager
        secret_name = self.SECRET_NAME_PATTERN.format(account_id=account_id)
        
        try:
            response = self.secrets_client.get_secret_value(SecretId=secret_name)
            secret_value = json.loads(response['SecretString'])
            external_id = secret_value['external_id']
            
            # Cache the external ID
            self._cache[account_id] = (external_id, time.time() + self.CACHE_TTL_SECONDS)
            
            return external_id
            
        except ClientError as e:
            if e.response['Error']['Code'] == 'ResourceNotFoundException':
                raise ValueError(f"External ID not found for account {account_id}")
            raise
    
    def rotate_external_id(self, account_id: str) -> str:
        """
        Rotate external ID for an account
        
        Args:
            account_id: AWS account ID (12 digits)
            
        Returns:
            New external ID
            
        Raises:
            ValueError: If account_id format is invalid
            ClientError: If Secrets Manager operation fails
            
        Requirements: REQ-9.5 (external ID rotation)
        """
        # Validate account ID format
        if not account_id.isdigit() or len(account_id) != 12:
            raise ValueError(f"Invalid account ID format: {account_id}")
        
        # Generate new external ID
        new_external_id = self.generate_external_id()
        
        # Retrieve existing secret to preserve metadata
        secret_name = self.SECRET_NAME_PATTERN.format(account_id=account_id)
        
        try:
            response = self.secrets_client.get_secret_value(SecretId=secret_name)
            secret_value = json.loads(response['SecretString'])
            
            # Update with new external ID
            secret_value['external_id'] = new_external_id
            secret_value['last_rotated'] = datetime.utcnow().isoformat() + "Z"
            
            # Update secret
            self.secrets_client.put_secret_value(
                SecretId=secret_name,
                SecretString=json.dumps(secret_value)
            )
            
            # Invalidate cache
            if account_id in self._cache:
                del self._cache[account_id]
            
            return new_external_id
            
        except ClientError as e:
            if e.response['Error']['Code'] == 'ResourceNotFoundException':
                raise ValueError(f"External ID not found for account {account_id}")
            raise
    
    def delete_external_id(self, account_id: str) -> None:
        """
        Delete external ID for an account
        
        Args:
            account_id: AWS account ID (12 digits)
            
        Raises:
            ValueError: If account_id format is invalid
            ClientError: If Secrets Manager operation fails
        """
        # Validate account ID format
        if not account_id.isdigit() or len(account_id) != 12:
            raise ValueError(f"Invalid account ID format: {account_id}")
        
        secret_name = self.SECRET_NAME_PATTERN.format(account_id=account_id)
        
        try:
            # Schedule deletion (7-day recovery window)
            self.secrets_client.delete_secret(
                SecretId=secret_name,
                RecoveryWindowInDays=7
            )
            
            # Invalidate cache
            if account_id in self._cache:
                del self._cache[account_id]
                
        except ClientError as e:
            if e.response['Error']['Code'] == 'ResourceNotFoundException':
                # Secret already deleted or doesn't exist
                pass
            else:
                raise
    
    def verify_encryption(self, account_id: str) -> bool:
        """
        Verify that external ID is encrypted with the correct KMS key
        
        Args:
            account_id: AWS account ID (12 digits)
            
        Returns:
            True if encrypted with correct key, False otherwise
            
        Validates: Property 39 (External ID Encryption)
        """
        secret_name = self.SECRET_NAME_PATTERN.format(account_id=account_id)
        
        try:
            response = self.secrets_client.describe_secret(SecretId=secret_name)
            
            # Check if KMS key ID matches
            secret_kms_key = response.get('KmsKeyId', '')
            
            # KMS key ID can be in different formats, normalize for comparison
            return self.kms_key_id in secret_kms_key or secret_kms_key.endswith(self.kms_key_id)
            
        except ClientError:
            return False
