/**
 * Compute Stack - Lambda Functions
 * 
 * Generated by: claude-3.5-sonnet
 * Timestamp: 2025-11-12T18:30:00Z
 * Version: 1.0.0
 * Policy Version: v1.0.0
 * Traceability: TASK-2 → RDS Discovery Service
 * Review Status: Pending
 * Risk Level: Level 2
 * 
 * Purpose: Define Lambda functions for RDS operations dashboard.
 * Starting with Discovery Service, will expand to include other services.
 */

import * as cdk from 'aws-cdk-lib';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as kms from 'aws-cdk-lib/aws-kms';
import { Construct } from 'constructs';

export interface ComputeStackProps extends cdk.StackProps {
  readonly lambdaExecutionRole: iam.IRole;
  readonly rdsInventoryTable: dynamodb.ITable;
  readonly metricsCacheTable: dynamodb.ITable;
  readonly healthAlertsTable: dynamodb.ITable;
  readonly auditLogTable: dynamodb.ITable;
  readonly approvalsTable: dynamodb.ITable;
  readonly onboardingStateTable: dynamodb.ITable;
  readonly onboardingAuditLogTable: dynamodb.ITable;
  readonly errorMetricsTable: dynamodb.ITable;
  readonly externalIdKmsKey: kms.IKey;
  readonly dataBucket: s3.IBucket;
  readonly externalId: string;
  readonly targetAccounts: string[];
  readonly targetRegions: string[];
  readonly snsTopicArn: string;
}

export class ComputeStack extends cdk.Stack {
  public readonly discoveryFunction: lambda.Function;
  public readonly healthMonitorFunction: lambda.Function;
  public readonly costAnalyzerFunction: lambda.Function;
  public readonly queryHandlerFunction: lambda.Function;
  public readonly complianceCheckerFunction: lambda.Function;
  public readonly operationsFunction: lambda.Function;
  public readonly cloudOpsGeneratorFunction: lambda.Function;
  public readonly monitoringFunction: lambda.Function;
  public readonly approvalWorkflowFunction: lambda.Function;
  public readonly accountDiscoveryFunction: lambda.Function;
  public readonly errorResolutionFunction: lambda.Function;
  public readonly monitoringDashboardFunction: lambda.Function;

  constructor(scope: Construct, id: string, props: ComputeStackProps) {
    super(scope, id, props);

    const { lambdaExecutionRole, rdsInventoryTable, metricsCacheTable,
            healthAlertsTable, auditLogTable, approvalsTable, onboardingStateTable,
            onboardingAuditLogTable, externalIdKmsKey, dataBucket, externalId,
            targetAccounts, targetRegions, snsTopicArn } = props;

    // ========================================
    // Lambda Function: RDS Discovery
    // ========================================
    this.discoveryFunction = new lambda.Function(this, 'DiscoveryFunction', {
      functionName: 'rds-discovery',
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/discovery'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(15),
      memorySize: 512,
      environment: {
        INVENTORY_TABLE: rdsInventoryTable.tableName,
        METRICS_CACHE_TABLE: metricsCacheTable.tableName,
        HEALTH_ALERTS_TABLE: healthAlertsTable.tableName,
        AUDIT_LOG_TABLE: auditLogTable.tableName,
        DATA_BUCKET: dataBucket.bucketName,
        EXTERNAL_ID: externalId,
        CROSS_ACCOUNT_ROLE_NAME: 'RDSDashboardCrossAccountRole',
        TARGET_ACCOUNTS: JSON.stringify(targetAccounts),
        TARGET_REGIONS: JSON.stringify(targetRegions),
        SNS_TOPIC_ARN: snsTopicArn,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO',
        METRICS_TTL_SECONDS: '300',
        CACHE_HIT_THRESHOLD: '0.7'
      },
      description: 'Discovers RDS instances across multiple accounts and regions',
    });

    // ========================================
    // Lambda Function: Health Monitor
    // ========================================
    this.healthMonitorFunction = new lambda.Function(this, 'HealthMonitorFunction', {
      functionName: 'rds-health-monitor',
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/health-monitor'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(15),
      memorySize: 512,
      environment: {
        INVENTORY_TABLE: rdsInventoryTable.tableName,
        METRICS_CACHE_TABLE: metricsCacheTable.tableName,
        HEALTH_ALERTS_TABLE: healthAlertsTable.tableName,
        AUDIT_LOG_TABLE: auditLogTable.tableName,
        DATA_BUCKET: dataBucket.bucketName,
        EXTERNAL_ID: externalId,
        CROSS_ACCOUNT_ROLE_NAME: 'RDSDashboardCrossAccountRole',
        TARGET_ACCOUNTS: JSON.stringify(targetAccounts),
        TARGET_REGIONS: JSON.stringify(targetRegions),
        SNS_TOPIC_ARN: snsTopicArn,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO',
        METRICS_TTL_SECONDS: '300',
        CACHE_HIT_THRESHOLD: '0.7'
      },
      description: 'Monitors RDS instance health and generates alerts',
    });

    // ========================================
    // Lambda Function: Cost Analyzer
    // ========================================
    this.costAnalyzerFunction = new lambda.Function(this, 'CostAnalyzerFunction', {
      functionName: 'rds-cost-analyzer',
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/cost-analyzer'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(15),
      memorySize: 1024,  // Higher memory for cost calculations
      environment: {
        INVENTORY_TABLE: rdsInventoryTable.tableName,
        METRICS_CACHE_TABLE: metricsCacheTable.tableName,
        HEALTH_ALERTS_TABLE: healthAlertsTable.tableName,
        AUDIT_LOG_TABLE: auditLogTable.tableName,
        DATA_BUCKET: dataBucket.bucketName,
        EXTERNAL_ID: externalId,
        CROSS_ACCOUNT_ROLE_NAME: 'RDSDashboardCrossAccountRole',
        TARGET_ACCOUNTS: JSON.stringify(targetAccounts),
        TARGET_REGIONS: JSON.stringify(targetRegions),
        SNS_TOPIC_ARN: snsTopicArn,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO'
      },
      description: 'Analyzes RDS costs and generates optimization recommendations',
    });

    // ========================================
    // Lambda Function: Query Handler
    // ========================================
    this.queryHandlerFunction = new lambda.Function(this, 'QueryHandlerFunction', {
      functionName: 'rds-query-handler',
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/query-handler'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.seconds(30),
      memorySize: 512,
      environment: {
        INVENTORY_TABLE: rdsInventoryTable.tableName,
        METRICS_CACHE_TABLE: metricsCacheTable.tableName,
        HEALTH_ALERTS_TABLE: healthAlertsTable.tableName,
        AUDIT_LOG_TABLE: auditLogTable.tableName,
        DATA_BUCKET: dataBucket.bucketName,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO'
      },
      description: 'Handles API queries for RDS dashboard data',
    });

    // ========================================
    // Lambda Function: Compliance Checker
    // ========================================
    this.complianceCheckerFunction = new lambda.Function(this, 'ComplianceCheckerFunction', {
      functionName: 'rds-compliance-checker',
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/compliance-checker'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(15),
      memorySize: 512,
      environment: {
        INVENTORY_TABLE: rdsInventoryTable.tableName,
        METRICS_CACHE_TABLE: metricsCacheTable.tableName,
        HEALTH_ALERTS_TABLE: healthAlertsTable.tableName,
        AUDIT_LOG_TABLE: auditLogTable.tableName,
        DATA_BUCKET: dataBucket.bucketName,
        EXTERNAL_ID: externalId,
        CROSS_ACCOUNT_ROLE_NAME: 'RDSDashboardCrossAccountRole',
        TARGET_ACCOUNTS: JSON.stringify(targetAccounts),
        TARGET_REGIONS: JSON.stringify(targetRegions),
        SNS_TOPIC_ARN: snsTopicArn,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO'
      },
      description: 'Checks RDS instances for compliance violations',
    });

    // ========================================
    // Lambda Function: Operations
    // ========================================
    this.operationsFunction = new lambda.Function(this, 'OperationsFunction', {
      functionName: 'rds-operations',
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/operations'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(5),
      memorySize: 512,
      environment: {
        INVENTORY_TABLE: rdsInventoryTable.tableName,
        METRICS_CACHE_TABLE: metricsCacheTable.tableName,
        HEALTH_ALERTS_TABLE: healthAlertsTable.tableName,
        AUDIT_LOG_TABLE: auditLogTable.tableName,
        DATA_BUCKET: dataBucket.bucketName,
        EXTERNAL_ID: externalId,
        CROSS_ACCOUNT_ROLE_NAME: 'RDSDashboardCrossAccountRole',
        SNS_TOPIC_ARN: snsTopicArn,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO'
      },
      description: 'Executes RDS operations (snapshots, reboots, etc.)',
    });

    // ========================================
    // Lambda Function: CloudOps Generator
    // ========================================
    this.cloudOpsGeneratorFunction = new lambda.Function(this, 'CloudOpsGeneratorFunction', {
      functionName: 'rds-cloudops-generator',
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/cloudops-generator'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(5),
      memorySize: 512,
      environment: {
        INVENTORY_TABLE: rdsInventoryTable.tableName,
        METRICS_CACHE_TABLE: metricsCacheTable.tableName,
        HEALTH_ALERTS_TABLE: healthAlertsTable.tableName,
        AUDIT_LOG_TABLE: auditLogTable.tableName,
        DATA_BUCKET: dataBucket.bucketName,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO'
      },
      description: 'Generates CloudOps request documents',
    });

    // ========================================
    // Lambda Function: Monitoring Service
    // ========================================
    this.monitoringFunction = new lambda.Function(this, 'MonitoringFunction', {
      functionName: 'rds-monitoring',
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/monitoring'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(5),
      memorySize: 512,
      environment: {
        EXTERNAL_ID: externalId,
        CROSS_ACCOUNT_ROLE_NAME: 'RDSDashboardCrossAccountRole',
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO'
      },
      description: 'Fetches CloudWatch metrics for RDS instances',
    });

    // ========================================
    // Lambda Function: Approval Workflow Service
    // ========================================
    this.approvalWorkflowFunction = new lambda.Function(this, 'ApprovalWorkflowFunction', {
      functionName: 'rds-approval-workflow',
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/approval-workflow'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(5),
      memorySize: 512,
      environment: {
        APPROVALS_TABLE: approvalsTable.tableName,
        AUDIT_LOG_TABLE: auditLogTable.tableName,
        SNS_TOPIC_ARN: snsTopicArn,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO'
      },
      description: 'Manages approval workflow for high-risk RDS operations',
    });

    // ========================================
    // Lambda Function: Account Discovery (Onboarding)
    // ========================================
    // Purpose: Discover new AWS accounts from Organizations and initiate onboarding
    // Requirements: REQ-1.1, REQ-1.2, REQ-1.3, REQ-1.4 (Account Discovery)
    this.accountDiscoveryFunction = new lambda.Function(this, 'AccountDiscoveryFunction', {
      functionName: 'rds-dashboard-account-discovery',
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'account_discovery.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/onboarding'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(5),
      memorySize: 512,
      environment: {
        ONBOARDING_STATE_TABLE: onboardingStateTable.tableName,
        ONBOARDING_AUDIT_LOG_TABLE: onboardingAuditLogTable.tableName,
        EXTERNAL_ID_KMS_KEY_ID: externalIdKmsKey.keyId,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard/Onboarding',
        LOG_LEVEL: 'INFO',
        MANAGEMENT_ACCOUNT_ID: this.account,
      },
      description: 'Discovers new AWS accounts and initiates automated onboarding',
    });

    // ========================================
    // Lambda Function: Error Resolution Handler
    // ========================================
    // Purpose: Handles API error detection, classification, and automated resolution
    // Requirements: REQ-1.1, REQ-1.2, REQ-2.1, REQ-2.2, REQ-2.3 (Error Resolution)
    this.errorResolutionFunction = new lambda.Function(this, 'ErrorResolutionFunction', {
      functionName: 'rds-dashboard-error-resolution',
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/error-resolution'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(5),
      memorySize: 1024,
      environment: {
        ERROR_METRICS_TABLE: props.errorMetricsTable.tableName,
        AUDIT_LOG_TABLE: props.auditLogTable.tableName,
        SNS_TOPIC_ARN: snsTopicArn,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard/ErrorResolution',
        LOG_LEVEL: 'INFO',
        CACHE_TTL: '300'
      },
      description: 'Detects, classifies, and automatically resolves API errors',
    });

    // ========================================
    // Lambda Function: Monitoring Dashboard
    // ========================================
    // Purpose: Provides real-time monitoring dashboard and metrics collection
    // Requirements: REQ-3.1, REQ-3.2, REQ-3.3 (Monitoring Dashboard)
    this.monitoringDashboardFunction = new lambda.Function(this, 'MonitoringDashboardFunction', {
      functionName: 'rds-dashboard-monitoring',
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/monitoring'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(2),
      memorySize: 512,
      environment: {
        ERROR_METRICS_TABLE: props.errorMetricsTable.tableName,
        METRICS_CACHE_TABLE: props.metricsCacheTable.tableName,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard/Monitoring',
        LOG_LEVEL: 'INFO'
      },
      description: 'Provides real-time monitoring dashboard and metrics collection',
    });

    // Grant permissions for account discovery Lambda
    onboardingStateTable.grantReadWriteData(this.accountDiscoveryFunction);
    onboardingAuditLogTable.grantReadWriteData(this.accountDiscoveryFunction);
    externalIdKmsKey.grantEncryptDecrypt(this.accountDiscoveryFunction);

    // Grant Organizations permissions
    this.accountDiscoveryFunction.addToRolePolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: [
        'organizations:ListAccounts',
        'organizations:DescribeAccount',
        'organizations:ListAccountsForParent',
        'organizations:DescribeOrganization',
      ],
      resources: ['*'],
    }));

    // Grant Secrets Manager permissions for external ID storage
    this.accountDiscoveryFunction.addToRolePolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: [
        'secretsmanager:CreateSecret',
        'secretsmanager:GetSecretValue',
        'secretsmanager:DescribeSecret',
        'secretsmanager:PutSecretValue',
        'secretsmanager:TagResource',
      ],
      resources: [`arn:aws:secretsmanager:${this.region}:${this.account}:secret:rds-dashboard/external-ids/*`],
    }));

    // Grant permissions for error resolution Lambda
    props.auditLogTable.grantReadWriteData(this.errorResolutionFunction);
    props.errorMetricsTable.grantReadWriteData(this.errorResolutionFunction);
    props.errorMetricsTable.grantReadWriteData(this.monitoringDashboardFunction);
    props.metricsCacheTable.grantReadWriteData(this.monitoringDashboardFunction);

    // Grant CloudWatch permissions for error resolution
    this.errorResolutionFunction.addToRolePolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: [
        'cloudwatch:PutMetricData',
        'cloudwatch:GetMetricStatistics',
        'cloudwatch:ListMetrics'
      ],
      resources: ['*'],
    }));

    // Grant SNS permissions for alerting
    this.errorResolutionFunction.addToRolePolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: ['sns:Publish'],
      resources: [snsTopicArn],
    }));

    // ========================================
    // CloudFormation Outputs
    // ========================================
    new cdk.CfnOutput(this, 'DiscoveryFunctionArn', {
      value: this.discoveryFunction.functionArn,
      description: 'ARN of RDS Discovery Lambda function',
      exportName: 'DiscoveryFunctionArn',
    });

    new cdk.CfnOutput(this, 'DiscoveryFunctionName', {
      value: this.discoveryFunction.functionName,
      description: 'Name of RDS Discovery Lambda function',
      exportName: 'DiscoveryFunctionName',
    });

    new cdk.CfnOutput(this, 'HealthMonitorFunctionArn', {
      value: this.healthMonitorFunction.functionArn,
      description: 'ARN of RDS Health Monitor Lambda function',
      exportName: 'HealthMonitorFunctionArn',
    });

    new cdk.CfnOutput(this, 'HealthMonitorFunctionName', {
      value: this.healthMonitorFunction.functionName,
      description: 'Name of RDS Health Monitor Lambda function',
      exportName: 'HealthMonitorFunctionName',
    });

    new cdk.CfnOutput(this, 'CostAnalyzerFunctionArn', {
      value: this.costAnalyzerFunction.functionArn,
      description: 'ARN of RDS Cost Analyzer Lambda function',
      exportName: 'CostAnalyzerFunctionArn',
    });

    new cdk.CfnOutput(this, 'CostAnalyzerFunctionName', {
      value: this.costAnalyzerFunction.functionName,
      description: 'Name of RDS Cost Analyzer Lambda function',
      exportName: 'CostAnalyzerFunctionName',
    });

    new cdk.CfnOutput(this, 'QueryHandlerFunctionArn', {
      value: this.queryHandlerFunction.functionArn,
      description: 'ARN of Query Handler Lambda function',
      exportName: 'QueryHandlerFunctionArn',
    });

    new cdk.CfnOutput(this, 'ComplianceCheckerFunctionArn', {
      value: this.complianceCheckerFunction.functionArn,
      description: 'ARN of Compliance Checker Lambda function',
      exportName: 'ComplianceCheckerFunctionArn',
    });

    new cdk.CfnOutput(this, 'OperationsFunctionArn', {
      value: this.operationsFunction.functionArn,
      description: 'ARN of Operations Lambda function',
      exportName: 'OperationsFunctionArn',
    });

    new cdk.CfnOutput(this, 'CloudOpsGeneratorFunctionArn', {
      value: this.cloudOpsGeneratorFunction.functionArn,
      description: 'ARN of CloudOps Generator Lambda function',
      exportName: 'CloudOpsGeneratorFunctionArn',
    });

    new cdk.CfnOutput(this, 'AccountDiscoveryFunctionArn', {
      value: this.accountDiscoveryFunction.functionArn,
      description: 'ARN of Account Discovery Lambda function',
      exportName: 'AccountDiscoveryFunctionArn',
    });

    new cdk.CfnOutput(this, 'AccountDiscoveryFunctionName', {
      value: this.accountDiscoveryFunction.functionName,
      description: 'Name of Account Discovery Lambda function',
      exportName: 'AccountDiscoveryFunctionName',
    });

    new cdk.CfnOutput(this, 'ErrorResolutionFunctionArn', {
      value: this.errorResolutionFunction.functionArn,
      description: 'ARN of Error Resolution Lambda function',
      exportName: 'ErrorResolutionFunctionArn',
    });

    new cdk.CfnOutput(this, 'ErrorResolutionFunctionName', {
      value: this.errorResolutionFunction.functionName,
      description: 'Name of Error Resolution Lambda function',
      exportName: 'ErrorResolutionFunctionName',
    });

    new cdk.CfnOutput(this, 'MonitoringDashboardFunctionArn', {
      value: this.monitoringDashboardFunction.functionArn,
      description: 'ARN of Monitoring Dashboard Lambda function',
      exportName: 'MonitoringDashboardFunctionArn',
    });

    new cdk.CfnOutput(this, 'MonitoringDashboardFunctionName', {
      value: this.monitoringDashboardFunction.functionName,
      description: 'Name of Monitoring Dashboard Lambda function',
      exportName: 'MonitoringDashboardFunctionName',
    });
  }
}
