/**
 * Compute Stack - Lambda Functions
 * 
 * Generated by: claude-3.5-sonnet
 * Timestamp: 2025-11-12T18:30:00Z
 * Version: 1.0.0
 * Policy Version: v1.0.0
 * Traceability: TASK-2 → RDS Discovery Service
 * Review Status: Pending
 * Risk Level: Level 2
 * 
 * Purpose: Define Lambda functions for RDS operations dashboard.
 * Starting with Discovery Service, will expand to include other services.
 */

import * as cdk from 'aws-cdk-lib';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as s3 from 'aws-cdk-lib/aws-s3';
import { Construct } from 'constructs';

export interface ComputeStackProps extends cdk.StackProps {
  readonly environment: string;
  readonly lambdaExecutionRole: iam.IRole;
  readonly rdsInventoryTable: dynamodb.ITable;
  readonly metricsCacheTable: dynamodb.ITable;
  readonly healthAlertsTable: dynamodb.ITable;
  readonly auditLogTable: dynamodb.ITable;
  readonly dataBucket: s3.IBucket;
  readonly externalId: string;
  readonly targetAccounts: string[];
  readonly targetRegions: string[];
  readonly snsTopicArn: string;
}

export class ComputeStack extends cdk.Stack {
  public readonly discoveryFunction: lambda.Function;
  public readonly healthMonitorFunction: lambda.Function;
  public readonly costAnalyzerFunction: lambda.Function;
  public readonly queryHandlerFunction: lambda.Function;
  public readonly complianceCheckerFunction: lambda.Function;
  public readonly operationsFunction: lambda.Function;
  public readonly cloudOpsGeneratorFunction: lambda.Function;

  constructor(scope: Construct, id: string, props: ComputeStackProps) {
    super(scope, id, props);

    const { environment, lambdaExecutionRole, rdsInventoryTable, metricsCacheTable,
            healthAlertsTable, auditLogTable, dataBucket, externalId,
            targetAccounts, targetRegions, snsTopicArn } = props;

    // ========================================
    // Lambda Function: RDS Discovery
    // ========================================
    this.discoveryFunction = new lambda.Function(this, 'DiscoveryFunction', {
      functionName: `rds-discovery-${environment}`,
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/discovery'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(15),
      memorySize: 512,
      environment: {
        ENVIRONMENT: environment,
        INVENTORY_TABLE: rdsInventoryTable.tableName,
        METRICS_CACHE_TABLE: metricsCacheTable.tableName,
        HEALTH_ALERTS_TABLE: healthAlertsTable.tableName,
        AUDIT_LOG_TABLE: auditLogTable.tableName,
        DATA_BUCKET: dataBucket.bucketName,
        EXTERNAL_ID: externalId,
        CROSS_ACCOUNT_ROLE_NAME: 'RDSDashboardCrossAccountRole',
        TARGET_ACCOUNTS: JSON.stringify(targetAccounts),
        TARGET_REGIONS: JSON.stringify(targetRegions),
        SNS_TOPIC_ARN: snsTopicArn,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO',
        METRICS_TTL_SECONDS: '300',
        CACHE_HIT_THRESHOLD: '0.7'
      },
      description: 'Discovers RDS instances across multiple accounts and regions',
    });

    // ========================================
    // Lambda Function: Health Monitor
    // ========================================
    this.healthMonitorFunction = new lambda.Function(this, 'HealthMonitorFunction', {
      functionName: `rds-health-monitor-${environment}`,
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/health-monitor'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(15),
      memorySize: 512,
      environment: {
        ENVIRONMENT: environment,
        INVENTORY_TABLE: rdsInventoryTable.tableName,
        METRICS_CACHE_TABLE: metricsCacheTable.tableName,
        HEALTH_ALERTS_TABLE: healthAlertsTable.tableName,
        AUDIT_LOG_TABLE: auditLogTable.tableName,
        DATA_BUCKET: dataBucket.bucketName,
        EXTERNAL_ID: externalId,
        CROSS_ACCOUNT_ROLE_NAME: 'RDSDashboardCrossAccountRole',
        TARGET_ACCOUNTS: JSON.stringify(targetAccounts),
        TARGET_REGIONS: JSON.stringify(targetRegions),
        SNS_TOPIC_ARN: snsTopicArn,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO',
        METRICS_TTL_SECONDS: '300',
        CACHE_HIT_THRESHOLD: '0.7'
      },
      description: 'Monitors RDS instance health and generates alerts',
    });

    // ========================================
    // Lambda Function: Cost Analyzer
    // ========================================
    this.costAnalyzerFunction = new lambda.Function(this, 'CostAnalyzerFunction', {
      functionName: `rds-cost-analyzer-${environment}`,
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/cost-analyzer'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(15),
      memorySize: 1024,  // Higher memory for cost calculations
      environment: {
        ENVIRONMENT: environment,
        INVENTORY_TABLE: rdsInventoryTable.tableName,
        METRICS_CACHE_TABLE: metricsCacheTable.tableName,
        HEALTH_ALERTS_TABLE: healthAlertsTable.tableName,
        AUDIT_LOG_TABLE: auditLogTable.tableName,
        DATA_BUCKET: dataBucket.bucketName,
        EXTERNAL_ID: externalId,
        CROSS_ACCOUNT_ROLE_NAME: 'RDSDashboardCrossAccountRole',
        TARGET_ACCOUNTS: JSON.stringify(targetAccounts),
        TARGET_REGIONS: JSON.stringify(targetRegions),
        SNS_TOPIC_ARN: snsTopicArn,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO'
      },
      description: 'Analyzes RDS costs and generates optimization recommendations',
    });

    // ========================================
    // Lambda Function: Query Handler
    // ========================================
    this.queryHandlerFunction = new lambda.Function(this, 'QueryHandlerFunction', {
      functionName: `rds-query-handler-${environment}`,
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/query-handler'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.seconds(30),
      memorySize: 512,
      environment: {
        ENVIRONMENT: environment,
        INVENTORY_TABLE: rdsInventoryTable.tableName,
        METRICS_CACHE_TABLE: metricsCacheTable.tableName,
        HEALTH_ALERTS_TABLE: healthAlertsTable.tableName,
        AUDIT_LOG_TABLE: auditLogTable.tableName,
        DATA_BUCKET: dataBucket.bucketName,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO'
      },
      description: 'Handles API queries for RDS dashboard data',
    });

    // ========================================
    // Lambda Function: Compliance Checker
    // ========================================
    this.complianceCheckerFunction = new lambda.Function(this, 'ComplianceCheckerFunction', {
      functionName: `rds-compliance-checker-${environment}`,
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/compliance-checker'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(15),
      memorySize: 512,
      environment: {
        ENVIRONMENT: environment,
        INVENTORY_TABLE: rdsInventoryTable.tableName,
        METRICS_CACHE_TABLE: metricsCacheTable.tableName,
        HEALTH_ALERTS_TABLE: healthAlertsTable.tableName,
        AUDIT_LOG_TABLE: auditLogTable.tableName,
        DATA_BUCKET: dataBucket.bucketName,
        EXTERNAL_ID: externalId,
        CROSS_ACCOUNT_ROLE_NAME: 'RDSDashboardCrossAccountRole',
        TARGET_ACCOUNTS: JSON.stringify(targetAccounts),
        TARGET_REGIONS: JSON.stringify(targetRegions),
        SNS_TOPIC_ARN: snsTopicArn,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO'
      },
      description: 'Checks RDS instances for compliance violations',
    });

    // ========================================
    // Lambda Function: Operations
    // ========================================
    this.operationsFunction = new lambda.Function(this, 'OperationsFunction', {
      functionName: `rds-operations-${environment}`,
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/operations'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(5),
      memorySize: 512,
      environment: {
        ENVIRONMENT: environment,
        INVENTORY_TABLE: rdsInventoryTable.tableName,
        METRICS_CACHE_TABLE: metricsCacheTable.tableName,
        HEALTH_ALERTS_TABLE: healthAlertsTable.tableName,
        AUDIT_LOG_TABLE: auditLogTable.tableName,
        DATA_BUCKET: dataBucket.bucketName,
        EXTERNAL_ID: externalId,
        CROSS_ACCOUNT_ROLE_NAME: 'RDSDashboardCrossAccountRole',
        SNS_TOPIC_ARN: snsTopicArn,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO'
      },
      description: 'Executes RDS operations (snapshots, reboots, etc.)',
    });

    // ========================================
    // Lambda Function: CloudOps Generator
    // ========================================
    this.cloudOpsGeneratorFunction = new lambda.Function(this, 'CloudOpsGeneratorFunction', {
      functionName: `rds-cloudops-generator-${environment}`,
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'handler.lambda_handler',
      code: lambda.Code.fromAsset('../lambda/cloudops-generator'),
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(5),
      memorySize: 512,
      environment: {
        ENVIRONMENT: environment,
        INVENTORY_TABLE: rdsInventoryTable.tableName,
        DATA_BUCKET: dataBucket.bucketName,
        CLOUDWATCH_NAMESPACE: 'RDSDashboard',
        LOG_LEVEL: 'INFO'
      },
      description: 'Generates CloudOps request documents',
    });

    // ========================================
    // CloudFormation Outputs
    // ========================================
    new cdk.CfnOutput(this, 'DiscoveryFunctionArn', {
      value: this.discoveryFunction.functionArn,
      description: 'ARN of RDS Discovery Lambda function',
      exportName: `${environment}-DiscoveryFunctionArn`,
    });

    new cdk.CfnOutput(this, 'DiscoveryFunctionName', {
      value: this.discoveryFunction.functionName,
      description: 'Name of RDS Discovery Lambda function',
      exportName: `${environment}-DiscoveryFunctionName`,
    });

    new cdk.CfnOutput(this, 'HealthMonitorFunctionArn', {
      value: this.healthMonitorFunction.functionArn,
      description: 'ARN of RDS Health Monitor Lambda function',
      exportName: `${environment}-HealthMonitorFunctionArn`,
    });

    new cdk.CfnOutput(this, 'HealthMonitorFunctionName', {
      value: this.healthMonitorFunction.functionName,
      description: 'Name of RDS Health Monitor Lambda function',
      exportName: `${environment}-HealthMonitorFunctionName`,
    });

    new cdk.CfnOutput(this, 'CostAnalyzerFunctionArn', {
      value: this.costAnalyzerFunction.functionArn,
      description: 'ARN of RDS Cost Analyzer Lambda function',
      exportName: `${environment}-CostAnalyzerFunctionArn`,
    });

    new cdk.CfnOutput(this, 'CostAnalyzerFunctionName', {
      value: this.costAnalyzerFunction.functionName,
      description: 'Name of RDS Cost Analyzer Lambda function',
      exportName: `${environment}-CostAnalyzerFunctionName`,
    });

    new cdk.CfnOutput(this, 'QueryHandlerFunctionArn', {
      value: this.queryHandlerFunction.functionArn,
      description: 'ARN of Query Handler Lambda function',
      exportName: `${environment}-QueryHandlerFunctionArn`,
    });

    new cdk.CfnOutput(this, 'ComplianceCheckerFunctionArn', {
      value: this.complianceCheckerFunction.functionArn,
      description: 'ARN of Compliance Checker Lambda function',
      exportName: `${environment}-ComplianceCheckerFunctionArn`,
    });

    new cdk.CfnOutput(this, 'OperationsFunctionArn', {
      value: this.operationsFunction.functionArn,
      description: 'ARN of Operations Lambda function',
      exportName: `${environment}-OperationsFunctionArn`,
    });

    new cdk.CfnOutput(this, 'CloudOpsGeneratorFunctionArn', {
      value: this.cloudOpsGeneratorFunction.functionArn,
      description: 'ARN of CloudOps Generator Lambda function',
      exportName: `${environment}-CloudOpsGeneratorFunctionArn`,
    });
  }
}
