/**
 * Orchestration Stack - EventBridge Scheduled Rules
 * 
 * Generated by: claude-3.5-sonnet
 * Timestamp: 2025-11-12T20:45:00Z
 * Version: 1.0.0
 * Policy Version: v1.0.0
 * Traceability: REQ-1.1, REQ-2.1, REQ-4.1, REQ-6.1 → DESIGN-001 → TASK-9
 * Review Status: Pending
 * Risk Level: Level 2
 * 
 * Purpose: Define EventBridge scheduled rules to automate Lambda function execution.
 * Implements hourly discovery, 5-minute health checks, and daily analysis tasks.
 * 
 * Design Decisions:
 * - Hourly discovery to catch new/changed instances
 * - 5-minute health monitoring for timely alerts
 * - Daily compliance and cost analysis (off-peak hours)
 * - Configurable schedules via config file
 */

import * as cdk from 'aws-cdk-lib';
import * as events from 'aws-cdk-lib/aws-events';
import * as targets from 'aws-cdk-lib/aws-events-targets';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export interface OrchestrationStackProps extends cdk.StackProps {
  readonly discoveryFunction: lambda.IFunction;
  readonly healthMonitorFunction?: lambda.IFunction;
  readonly costAnalyzerFunction?: lambda.IFunction;
  readonly complianceCheckerFunction?: lambda.IFunction;
  readonly discoverySchedule: string;
  readonly healthMonitorSchedule: string;
}

export class OrchestrationStack extends cdk.Stack {
  public readonly discoveryRule: events.Rule;
  public readonly healthMonitorRule?: events.Rule;

  constructor(scope: Construct, id: string, props: OrchestrationStackProps) {
    super(scope, id, props);

    const { discoveryFunction, healthMonitorFunction,
            costAnalyzerFunction, complianceCheckerFunction,
            discoverySchedule, healthMonitorSchedule } = props;

    // ========================================
    // EventBridge Rule: RDS Discovery (Hourly)
    // ========================================
    // Purpose: Automatically discover RDS instances across accounts/regions
    // Requirements: REQ-1.1 (automated discovery)
    this.discoveryRule = new events.Rule(this, 'DiscoveryScheduleRule', {
      ruleName: 'rds-discovery-schedule',
      description: 'Triggers RDS discovery Lambda function hourly',
      schedule: events.Schedule.expression(discoverySchedule),
      enabled: true,
    });

    // Add discovery Lambda as target
    this.discoveryRule.addTarget(new targets.LambdaFunction(discoveryFunction, {
      retryAttempts: 2,
      maxEventAge: cdk.Duration.hours(2),
    }));

    // ========================================
    // EventBridge Rule: Health Monitor (Every 5 minutes)
    // ========================================
    // Purpose: Monitor RDS health metrics and generate alerts
    // Requirements: REQ-2.1 (health monitoring)
    if (healthMonitorFunction) {
      this.healthMonitorRule = new events.Rule(this, 'HealthMonitorScheduleRule', {
        ruleName: 'rds-health-monitor-schedule',
        description: 'Triggers RDS health monitor Lambda function every 5 minutes',
        schedule: events.Schedule.expression(healthMonitorSchedule),
        enabled: true,
      });

      // Add health monitor Lambda as target
      this.healthMonitorRule.addTarget(new targets.LambdaFunction(healthMonitorFunction, {
        retryAttempts: 2,
        maxEventAge: cdk.Duration.minutes(30),
      }));
    }

    // ========================================
    // EventBridge Rule: Compliance Checker (Daily at 02:00 SGT)
    // ========================================
    // Purpose: Check RDS compliance daily
    // Requirements: REQ-6.1 (compliance checking)
    if (complianceCheckerFunction) {
      const complianceRule = new events.Rule(this, 'ComplianceScheduleRule', {
        ruleName: 'rds-compliance-schedule',
        description: 'Triggers RDS compliance checker Lambda function daily at 02:00 SGT',
        schedule: events.Schedule.cron({
          minute: '0',
          hour: '18',  // 02:00 SGT = 18:00 UTC (UTC+8)
          day: '*',
          month: '*',
          year: '*',
        }),
        enabled: true,
      });

      complianceRule.addTarget(new targets.LambdaFunction(complianceCheckerFunction, {
        retryAttempts: 2,
        maxEventAge: cdk.Duration.hours(6),
      }));
    }

    // ========================================
    // EventBridge Rule: Cost Analyzer (Daily at 03:00 SGT)
    // ========================================
    // Purpose: Analyze RDS costs daily
    // Requirements: REQ-4.1 (cost analysis)
    if (costAnalyzerFunction) {
      const costAnalyzerRule = new events.Rule(this, 'CostAnalyzerScheduleRule', {
        ruleName: 'rds-cost-analyzer-schedule',
        description: 'Triggers RDS cost analyzer Lambda function daily at 03:00 SGT',
        schedule: events.Schedule.cron({
          minute: '0',
          hour: '19',  // 03:00 SGT = 19:00 UTC (UTC+8)
          day: '*',
          month: '*',
          year: '*',
        }),
        enabled: true,
      });

      costAnalyzerRule.addTarget(new targets.LambdaFunction(costAnalyzerFunction, {
        retryAttempts: 2,
        maxEventAge: cdk.Duration.hours(6),
      }));
    }

    // ========================================
    // CloudFormation Outputs
    // ========================================
    new cdk.CfnOutput(this, 'DiscoveryRuleName', {
      value: this.discoveryRule.ruleName,
      description: 'EventBridge rule name for RDS discovery',
      exportName: 'DiscoveryRuleName',
    });

    if (this.healthMonitorRule) {
      new cdk.CfnOutput(this, 'HealthMonitorRuleName', {
        value: this.healthMonitorRule.ruleName,
        description: 'EventBridge rule name for health monitoring',
        exportName: 'HealthMonitorRuleName',
      });
    }

    // Add tags
    cdk.Tags.of(this).add('Component', 'Orchestration');
  }
}
