/*
 * WAF Stack - Web Application Firewall
 * 
 * Generated by: claude-3.5-sonnet
 * Timestamp: 2025-12-03T00:00:00Z
 * Version: 1.0.0
 * Policy Version: v1.0.0
 * Traceability: REQ-6.1 → DESIGN-6.1 → TASK-9.1
 * Review Status: Pending
 * Risk Level: Level 2
 * 
 * Purpose: Deploy AWS WAF to protect API Gateway and CloudFront distributions
 * from common web exploits and attacks.
 * 
 * Features:
 * - OWASP Top 10 protection
 * - Rate limiting (100 requests per 5 minutes per IP)
 * - Geo-blocking capabilities
 * - SQL injection and XSS protection
 * - Bot control
 */

import * as cdk from 'aws-cdk-lib';
import * as wafv2 from 'aws-cdk-lib/aws-wafv2';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';
import { Construct } from 'constructs';

export interface WafStackProps extends cdk.StackProps {
  /**
   * API Gateway REST API to protect
   */
  apiGateway?: apigateway.RestApi;
  
  /**
   * Rate limit per IP (requests per 5 minutes)
   * Default: 100
   */
  rateLimit?: number;
  
  /**
   * List of country codes to block (ISO 3166-1 alpha-2)
   * Example: ['CN', 'RU']
   */
  blockedCountries?: string[];
  
  /**
   * Enable AWS Managed Rules for OWASP Top 10
   * Default: true
   */
  enableOWASPRules?: boolean;
  
  /**
   * Enable bot control
   * Default: true
   */
  enableBotControl?: boolean;
}

export class WafStack extends cdk.Stack {
  public readonly webAcl: wafv2.CfnWebACL;
  public readonly webAclArn: string;

  constructor(scope: Construct, id: string, props: WafStackProps) {
    super(scope, id, props);

    const rateLimit = props.rateLimit ?? 100;
    const blockedCountries = props.blockedCountries ?? [];
    const enableOWASPRules = props.enableOWASPRules ?? true;
    const enableBotControl = props.enableBotControl ?? true;

    // Build rules array
    const rules: wafv2.CfnWebACL.RuleProperty[] = [];
    let priority = 0;

    // Rule 0: Allow BFF requests (whitelist)
    rules.push({
      name: 'AllowBFFRequests',
      priority: priority++,
      statement: {
        byteMatchStatement: {
          searchString: 'true',
          fieldToMatch: {
            singleHeader: {
              name: 'x-bff-request',
            },
          },
          textTransformations: [
            {
              priority: 0,
              type: 'NONE',
            },
          ],
          positionalConstraint: 'EXACTLY',
        },
      },
      action: {
        allow: {},
      },
      visibilityConfig: {
        sampledRequestsEnabled: true,
        cloudWatchMetricsEnabled: true,
        metricName: 'AllowBFFRequests',
      },
    });

    // Rule 1: Rate limiting
    rules.push({
      name: 'RateLimitRule',
      priority: priority++,
      statement: {
        rateBasedStatement: {
          limit: rateLimit,
          aggregateKeyType: 'IP',
        },
      },
      action: {
        block: {
          customResponse: {
            responseCode: 429,
            customResponseBodyKey: 'RateLimitExceeded',
          },
        },
      },
      visibilityConfig: {
        sampledRequestsEnabled: true,
        cloudWatchMetricsEnabled: true,
        metricName: 'RateLimitRule',
      },
    });

    // Rule 2: Geo-blocking (if countries specified)
    if (blockedCountries.length > 0) {
      rules.push({
        name: 'GeoBlockingRule',
        priority: priority++,
        statement: {
          geoMatchStatement: {
            countryCodes: blockedCountries,
          },
        },
        action: {
          block: {
            customResponse: {
              responseCode: 403,
              customResponseBodyKey: 'GeoBlocked',
            },
          },
        },
        visibilityConfig: {
          sampledRequestsEnabled: true,
          cloudWatchMetricsEnabled: true,
          metricName: 'GeoBlockingRule',
        },
      });
    }

    // Rule 3: AWS Managed Rules - Core Rule Set (OWASP Top 10)
    if (enableOWASPRules) {
      rules.push({
        name: 'AWSManagedRulesCommonRuleSet',
        priority: priority++,
        statement: {
          managedRuleGroupStatement: {
            vendorName: 'AWS',
            name: 'AWSManagedRulesCommonRuleSet',
            // Exclude rules that might cause false positives
            excludedRules: [
              { name: 'SizeRestrictions_BODY' }, // Allow larger request bodies
              { name: 'GenericRFI_BODY' }, // Can cause false positives with JSON
            ],
          },
        },
        overrideAction: {
          none: {},
        },
        visibilityConfig: {
          sampledRequestsEnabled: true,
          cloudWatchMetricsEnabled: true,
          metricName: 'AWSManagedRulesCommonRuleSet',
        },
      });

      // Rule 4: AWS Managed Rules - Known Bad Inputs
      rules.push({
        name: 'AWSManagedRulesKnownBadInputsRuleSet',
        priority: priority++,
        statement: {
          managedRuleGroupStatement: {
            vendorName: 'AWS',
            name: 'AWSManagedRulesKnownBadInputsRuleSet',
          },
        },
        overrideAction: {
          none: {},
        },
        visibilityConfig: {
          sampledRequestsEnabled: true,
          cloudWatchMetricsEnabled: true,
          metricName: 'AWSManagedRulesKnownBadInputsRuleSet',
        },
      });

      // Rule 5: AWS Managed Rules - SQL Injection
      rules.push({
        name: 'AWSManagedRulesSQLiRuleSet',
        priority: priority++,
        statement: {
          managedRuleGroupStatement: {
            vendorName: 'AWS',
            name: 'AWSManagedRulesSQLiRuleSet',
          },
        },
        overrideAction: {
          none: {},
        },
        visibilityConfig: {
          sampledRequestsEnabled: true,
          cloudWatchMetricsEnabled: true,
          metricName: 'AWSManagedRulesSQLiRuleSet',
        },
      });
    }

    // Rule 6: Bot Control (if enabled)
    if (enableBotControl) {
      rules.push({
        name: 'AWSManagedRulesBotControlRuleSet',
        priority: priority++,
        statement: {
          managedRuleGroupStatement: {
            vendorName: 'AWS',
            name: 'AWSManagedRulesBotControlRuleSet',
            // Configure bot control
            managedRuleGroupConfigs: [
              {
                awsManagedRulesBotControlRuleSet: {
                  inspectionLevel: 'COMMON', // COMMON or TARGETED
                },
              },
            ],
          },
        },
        overrideAction: {
          none: {},
        },
        visibilityConfig: {
          sampledRequestsEnabled: true,
          cloudWatchMetricsEnabled: true,
          metricName: 'AWSManagedRulesBotControlRuleSet',
        },
      });
    }

    // Create Web ACL
    this.webAcl = new wafv2.CfnWebACL(this, 'WebACL', {
      name: `${id}-WebACL`,
      scope: 'REGIONAL', // Use 'CLOUDFRONT' for CloudFront distributions
      defaultAction: {
        allow: {}, // Allow by default, block based on rules
      },
      rules,
      visibilityConfig: {
        sampledRequestsEnabled: true,
        cloudWatchMetricsEnabled: true,
        metricName: 'WebACL',
      },
      customResponseBodies: {
        RateLimitExceeded: {
          contentType: 'APPLICATION_JSON',
          content: JSON.stringify({
            error: 'Rate limit exceeded',
            message: 'Too many requests. Please try again later.',
          }),
        },
        GeoBlocked: {
          contentType: 'APPLICATION_JSON',
          content: JSON.stringify({
            error: 'Access denied',
            message: 'Access from your location is not permitted.',
          }),
        },
      },
    });

    this.webAclArn = this.webAcl.attrArn;

    // Associate with API Gateway if provided
    if (props.apiGateway) {
      const stage = props.apiGateway.deploymentStage;
      const stageArn = `arn:aws:apigateway:${this.region}::/restapis/${props.apiGateway.restApiId}/stages/${stage.stageName}`;

      new wafv2.CfnWebACLAssociation(this, 'WebACLAssociation', {
        resourceArn: stageArn,
        webAclArn: this.webAclArn,
      });

      new cdk.CfnOutput(this, 'WebACLAssociatedWithAPI', {
        value: props.apiGateway.restApiId,
        description: 'API Gateway protected by WAF',
      });
    }

    // Outputs
    new cdk.CfnOutput(this, 'WebACLId', {
      value: this.webAcl.attrId,
      description: 'WAF Web ACL ID',
      exportName: `${id}-WebACLId`,
    });

    new cdk.CfnOutput(this, 'WebACLArn', {
      value: this.webAclArn,
      description: 'WAF Web ACL ARN',
      exportName: `${id}-WebACLArn`,
    });

    // CloudWatch Dashboard for WAF metrics
    this.createWafDashboard();

    // Tags
    cdk.Tags.of(this).add('Component', 'Security');
    cdk.Tags.of(this).add('ManagedBy', 'CDK');
    cdk.Tags.of(this).add('Purpose', 'WAF Protection');
  }

  private createWafDashboard(): void {
    // Note: CloudWatch Dashboard creation would go here
    // For now, we'll rely on the built-in WAF metrics in CloudWatch
    
    // Key metrics to monitor:
    // - AllowedRequests
    // - BlockedRequests
    // - CountedRequests
    // - PassedRequests
    // - RateLimitRule (custom metric)
    // - GeoBlockingRule (custom metric)
    
    // These are automatically available in CloudWatch under AWS/WAFV2
  }
}
