/**
 * Configuration Loader for CDK
 * 
 * Generated by: claude-3.5-sonnet
 * Timestamp: 2025-11-12T18:45:00Z
 * Version: 1.0.0
 * 
 * Purpose: Load and validate dashboard configuration from JSON file.
 * Provides type-safe access to configuration values.
 */

import * as fs from 'fs';
import * as path from 'path';

export interface AccountConfig {
  account_id: string;
  account_name: string;
  enabled: boolean;
}

export interface RegionConfig {
  region: string;
  region_name: string;
  enabled: boolean;
  priority: number;
}

export interface DashboardConfig {
  version: string;
  description: string;
  last_updated: string;
  
  deployment: {
    environment: string;
    region: string;
    management_account_id: string;
  };
  
  cross_account: {
    external_id: string;
    role_name: string;
    target_accounts: AccountConfig[];
    target_regions: RegionConfig[];
  };
  
  discovery: {
    schedule: string;
    timeout_minutes: number;
    memory_mb: number;
    parallel_workers: number;
    retry_attempts: number;
  };
  
  monitoring: {
    cloudwatch_namespace: string;
    sns_email: string;
    alert_thresholds: {
      new_instances_threshold: number;
      deleted_instances_threshold: number;
      error_rate_threshold: number;
    };
  };
  
  caching: {
    metrics_ttl_seconds: number;
    cache_hit_threshold: number;
  };
  
  logging: {
    log_level: string;
    log_retention_days: number;
  };
  
  tags: {
    [key: string]: string;
  };
}

export class ConfigLoader {
  private static instance: DashboardConfig | null = null;
  
  /**
   * Load configuration from JSON file.
   * Configuration is cached after first load.
   */
  static load(configPath?: string): DashboardConfig {
    if (this.instance) {
      return this.instance;
    }
    
    const defaultPath = path.join(__dirname, 'dashboard-config.json');
    const filePath = configPath || defaultPath;
    
    try {
      const fileContent = fs.readFileSync(filePath, 'utf-8');
      const config = JSON.parse(fileContent) as DashboardConfig;
      
      // Validate configuration
      this.validateConfig(config);
      
      this.instance = config;
      return config;
      
    } catch (error) {
      throw new Error(`Failed to load configuration from ${filePath}: ${error}`);
    }
  }
  
  /**
   * Get enabled target accounts.
   */
  static getEnabledAccounts(config: DashboardConfig): string[] {
    return config.cross_account.target_accounts
      .filter(account => account.enabled)
      .map(account => account.account_id);
  }
  
  /**
   * Get enabled target regions sorted by priority.
   */
  static getEnabledRegions(config: DashboardConfig): string[] {
    return config.cross_account.target_regions
      .filter(region => region.enabled)
      .sort((a, b) => a.priority - b.priority)
      .map(region => region.region);
  }
  
  /**
   * Validate configuration structure and values.
   */
  private static validateConfig(config: DashboardConfig): void {
    // Check required fields
    if (!config.deployment?.environment) {
      throw new Error('Missing required field: deployment.environment');
    }
    
    if (!config.deployment?.region) {
      throw new Error('Missing required field: deployment.region');
    }
    
    if (!config.cross_account?.external_id) {
      throw new Error('Missing required field: cross_account.external_id');
    }
    
    // Validate at least one account is enabled
    const enabledAccounts = config.cross_account.target_accounts.filter(a => a.enabled);
    if (enabledAccounts.length === 0) {
      throw new Error('At least one target account must be enabled');
    }
    
    // Validate at least one region is enabled
    const enabledRegions = config.cross_account.target_regions.filter(r => r.enabled);
    if (enabledRegions.length === 0) {
      throw new Error('At least one target region must be enabled');
    }
    
    // Validate account IDs format
    enabledAccounts.forEach(account => {
      if (!/^\d{12}$/.test(account.account_id)) {
        throw new Error(`Invalid account ID format: ${account.account_id}`);
      }
    });
    
    console.log('✓ Configuration validated successfully');
    console.log(`  Environment: ${config.deployment.environment}`);
    console.log(`  Enabled Accounts: ${enabledAccounts.length}`);
    console.log(`  Enabled Regions: ${enabledRegions.length}`);
  }
  
  /**
   * Clear cached configuration (useful for testing).
   */
  static clearCache(): void {
    this.instance = null;
  }
}
