#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Diagnose Production API Issues

.DESCRIPTION
    Systematically diagnose the 500 and 403 errors in the RDS Operations Dashboard.
    This script checks API Gateway routes, Lambda functions, and configurations.

.NOTES
    Generated by: claude-3.5-sonnet
    Timestamp: 2025-12-20T14:30:00Z
    Version: 1.0.0
    Traceability: Production API Fixes Task 1
#>

param(
    [switch]$Verbose,
    [switch]$FixIssues
)

# Set error action preference
$ErrorActionPreference = "Continue"

Write-Host "🔍 RDS Operations Dashboard - Production API Diagnostics" -ForegroundColor Cyan
Write-Host "=" * 60

# Function to test API endpoint
function Test-ApiEndpoint {
    param(
        [string]$Url,
        [string]$Method = "GET",
        [hashtable]$Headers = @{},
        [string]$Body = $null
    )
    
    try {
        $params = @{
            Uri = $Url
            Method = $Method
            Headers = $Headers
            TimeoutSec = 10
        }
        
        if ($Body) {
            $params.Body = $Body
            $params.ContentType = "application/json"
        }
        
        $response = Invoke-RestMethod @params
        return @{
            Success = $true
            StatusCode = 200
            Response = $response
        }
    }
    catch {
        return @{
            Success = $false
            StatusCode = $_.Exception.Response.StatusCode.value__
            Error = $_.Exception.Message
            Response = $_.Exception.Response
        }
    }
}

# Function to check Lambda function
function Test-LambdaFunction {
    param([string]$FunctionName)
    
    try {
        $function = aws lambda get-function --function-name $FunctionName 2>$null | ConvertFrom-Json
        if ($function) {
            return @{
                Exists = $true
                State = $function.Configuration.State
                LastModified = $function.Configuration.LastModified
                Runtime = $function.Configuration.Runtime
                Handler = $function.Configuration.Handler
            }
        }
    }
    catch {
        return @{
            Exists = $false
            Error = $_.Exception.Message
        }
    }
}

# Function to check API Gateway
function Test-ApiGateway {
    param([string]$ApiId)
    
    try {
        $api = aws apigateway get-rest-api --rest-api-id $ApiId 2>$null | ConvertFrom-Json
        if ($api) {
            $resources = aws apigateway get-resources --rest-api-id $ApiId 2>$null | ConvertFrom-Json
            return @{
                Exists = $true
                Name = $api.name
                CreatedDate = $api.createdDate
                Resources = $resources.items
            }
        }
    }
    catch {
        return @{
            Exists = $false
            Error = $_.Exception.Message
        }
    }
}

Write-Host "📋 Step 1: Checking Environment Configuration" -ForegroundColor Yellow

# Check AWS CLI configuration
Write-Host "  ✓ Checking AWS CLI..." -NoNewline
try {
    $awsIdentity = aws sts get-caller-identity 2>$null | ConvertFrom-Json
    Write-Host " OK" -ForegroundColor Green
    Write-Host "    Account: $($awsIdentity.Account)" -ForegroundColor Gray
    Write-Host "    User: $($awsIdentity.Arn)" -ForegroundColor Gray
}
catch {
    Write-Host " FAILED" -ForegroundColor Red
    Write-Host "    Error: AWS CLI not configured or accessible" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "📋 Step 2: Checking API Gateway Configuration" -ForegroundColor Yellow

# Get API Gateway ID from CloudFormation or environment
$apiGatewayId = $null
try {
    $stacks = aws cloudformation describe-stacks --query "Stacks[?contains(StackName, 'ApiStack')].Outputs" 2>$null | ConvertFrom-Json
    foreach ($stack in $stacks) {
        foreach ($output in $stack) {
            if ($output.OutputKey -eq "ApiUrl") {
                $apiUrl = $output.OutputValue
                $apiGatewayId = ($apiUrl -split "/")[2] -split "\." | Select-Object -First 1
                break
            }
        }
    }
}
catch {
    Write-Host "  ⚠️  Could not find API Gateway ID from CloudFormation" -ForegroundColor Yellow
}

if ($apiGatewayId) {
    Write-Host "  ✓ Found API Gateway ID: $apiGatewayId" -ForegroundColor Green
    
    # Check API Gateway resources
    $apiInfo = Test-ApiGateway -ApiId $apiGatewayId
    if ($apiInfo.Exists) {
        Write-Host "  ✓ API Gateway exists: $($apiInfo.Name)" -ForegroundColor Green
        
        # Check for error-resolution routes
        $errorResolutionRoutes = $apiInfo.Resources | Where-Object { $_.pathPart -eq "error-resolution" }
        if ($errorResolutionRoutes) {
            Write-Host "  ✓ Found error-resolution resource" -ForegroundColor Green
            
            # Check for statistics sub-resource
            $statisticsRoutes = $apiInfo.Resources | Where-Object { $_.pathPart -eq "statistics" }
            if ($statisticsRoutes) {
                Write-Host "  ✓ Found statistics resource" -ForegroundColor Green
            }
            else {
                Write-Host "  ❌ Missing statistics resource under error-resolution" -ForegroundColor Red
            }
        }
        else {
            Write-Host "  ❌ Missing error-resolution resource" -ForegroundColor Red
        }
        
        # Check for operations routes
        $operationsRoutes = $apiInfo.Resources | Where-Object { $_.pathPart -eq "operations" }
        if ($operationsRoutes) {
            Write-Host "  ✓ Found operations resource" -ForegroundColor Green
        }
        else {
            Write-Host "  ❌ Missing operations resource" -ForegroundColor Red
        }
    }
    else {
        Write-Host "  ❌ API Gateway not accessible: $($apiInfo.Error)" -ForegroundColor Red
    }
}
else {
    Write-Host "  ❌ Could not determine API Gateway ID" -ForegroundColor Red
}

Write-Host ""
Write-Host "📋 Step 3: Checking Lambda Functions" -ForegroundColor Yellow

# Check key Lambda functions
$lambdaFunctions = @(
    "rds-operations",
    "rds-health-monitor", 
    "rds-dashboard-bff",
    "rds-monitoring-dashboard",
    "rds-error-resolution"
)

foreach ($functionName in $lambdaFunctions) {
    Write-Host "  Checking $functionName..." -NoNewline
    $lambdaInfo = Test-LambdaFunction -FunctionName $functionName
    
    if ($lambdaInfo.Exists) {
        Write-Host " ✓ EXISTS" -ForegroundColor Green
        if ($Verbose) {
            Write-Host "    State: $($lambdaInfo.State)" -ForegroundColor Gray
            Write-Host "    Runtime: $($lambdaInfo.Runtime)" -ForegroundColor Gray
            Write-Host "    Last Modified: $($lambdaInfo.LastModified)" -ForegroundColor Gray
        }
    }
    else {
        Write-Host " ❌ NOT FOUND" -ForegroundColor Red
        if ($lambdaInfo.Error) {
            Write-Host "    Error: $($lambdaInfo.Error)" -ForegroundColor Red
        }
    }
}

Write-Host ""
Write-Host "📋 Step 4: Testing API Endpoints" -ForegroundColor Yellow

# Test BFF endpoints
$bffUrl = "https://km9ww1hh3k.execute-api.ap-southeast-1.amazonaws.com"

Write-Host "  Testing BFF Health..." -NoNewline
$healthTest = Test-ApiEndpoint -Url "$bffUrl/health"
if ($healthTest.Success) {
    Write-Host " ✓ OK" -ForegroundColor Green
}
else {
    Write-Host " ❌ FAILED ($($healthTest.StatusCode))" -ForegroundColor Red
    if ($Verbose) {
        Write-Host "    Error: $($healthTest.Error)" -ForegroundColor Red
    }
}

Write-Host "  Testing Error Statistics (without auth)..." -NoNewline
$statsTest = Test-ApiEndpoint -Url "$bffUrl/api/errors/statistics"
if ($statsTest.Success) {
    Write-Host " ✓ OK" -ForegroundColor Green
}
else {
    Write-Host " ❌ FAILED ($($statsTest.StatusCode))" -ForegroundColor Red
    if ($Verbose) {
        Write-Host "    Error: $($statsTest.Error)" -ForegroundColor Red
    }
}

Write-Host "  Testing Operations (without auth)..." -NoNewline
$opsTest = Test-ApiEndpoint -Url "$bffUrl/api/operations" -Method "POST" -Body '{"operation_type":"create_snapshot","instance_id":"test"}'
if ($opsTest.Success) {
    Write-Host " ✓ OK" -ForegroundColor Green
}
else {
    Write-Host " ❌ FAILED ($($opsTest.StatusCode))" -ForegroundColor Red
    if ($Verbose) {
        Write-Host "    Error: $($opsTest.Error)" -ForegroundColor Red
    }
}

Write-Host ""
Write-Host "📋 Step 5: Checking Backend API Gateway" -ForegroundColor Yellow

$backendUrl = "https://qxx9whmsd4.execute-api.ap-southeast-1.amazonaws.com"

# We need an API key to test backend endpoints
Write-Host "  ⚠️  Backend API requires API key - cannot test without authentication" -ForegroundColor Yellow

Write-Host ""
Write-Host "📋 Step 6: Analyzing Configuration Files" -ForegroundColor Yellow

# Check dashboard config
$configPath = "config/dashboard-config.json"
if (Test-Path $configPath) {
    Write-Host "  ✓ Found dashboard config: $configPath" -ForegroundColor Green
    
    try {
        $config = Get-Content $configPath | ConvertFrom-Json
        $productionOpsEnabled = $config.operations.enable_production_operations
        Write-Host "    Production operations enabled: $productionOpsEnabled" -ForegroundColor $(if ($productionOpsEnabled) { "Green" } else { "Yellow" })
    }
    catch {
        Write-Host "  ❌ Could not parse dashboard config" -ForegroundColor Red
    }
}
else {
    Write-Host "  ❌ Dashboard config not found: $configPath" -ForegroundColor Red
}

# Check BFF environment
Write-Host "  Checking BFF environment variables..." -NoNewline
$bffEnvPath = "bff/.env"
if (Test-Path $bffEnvPath) {
    Write-Host " ✓ Found" -ForegroundColor Green
    
    if ($Verbose) {
        $envContent = Get-Content $bffEnvPath
        foreach ($line in $envContent) {
            if ($line -match "^[A-Z_]+=") {
                $key = ($line -split "=")[0]
                Write-Host "    $key" -ForegroundColor Gray
            }
        }
    }
}
else {
    Write-Host " ❌ Not found" -ForegroundColor Red
}

Write-Host ""
Write-Host "📋 Step 7: Summary of Issues Found" -ForegroundColor Yellow

$issues = @()

# Collect issues based on tests
if (-not $healthTest.Success) {
    $issues += "BFF Health endpoint failing"
}

if (-not $statsTest.Success) {
    $issues += "Error statistics endpoint returning $($statsTest.StatusCode)"
}

if (-not $opsTest.Success -and $opsTest.StatusCode -eq 403) {
    $issues += "Operations endpoint returning 403 Forbidden"
}

if ($issues.Count -eq 0) {
    Write-Host "  ✅ No critical issues detected!" -ForegroundColor Green
}
else {
    Write-Host "  ❌ Issues detected:" -ForegroundColor Red
    foreach ($issue in $issues) {
        Write-Host "    • $issue" -ForegroundColor Red
    }
}

Write-Host ""
Write-Host "📋 Step 8: Recommendations" -ForegroundColor Yellow

Write-Host "  Based on the analysis:" -ForegroundColor White

if ($statsTest.StatusCode -eq 500) {
    Write-Host "  1. 500 Error on /api/errors/statistics:" -ForegroundColor Yellow
    Write-Host "     • Check if error-resolution Lambda function exists and is deployed" -ForegroundColor Gray
    Write-Host "     • Verify API Gateway route mapping to correct Lambda function" -ForegroundColor Gray
    Write-Host "     • Check Lambda function logs for runtime errors" -ForegroundColor Gray
}

if ($opsTest.StatusCode -eq 403) {
    Write-Host "  2. 403 Error on /api/operations:" -ForegroundColor Yellow
    Write-Host "     • Verify JWT token is being passed correctly" -ForegroundColor Gray
    Write-Host "     • Check user permissions and Cognito group membership" -ForegroundColor Gray
    Write-Host "     • Ensure production operations are properly configured" -ForegroundColor Gray
}

Write-Host "  3. Next steps:" -ForegroundColor Yellow
Write-Host "     • Check CloudWatch logs for detailed error messages" -ForegroundColor Gray
Write-Host "     • Verify Lambda function environment variables" -ForegroundColor Gray
Write-Host "     • Test with proper authentication tokens" -ForegroundColor Gray

Write-Host ""
Write-Host "🔍 Diagnostic Complete" -ForegroundColor Cyan
Write-Host "=" * 60