# S3 Bucket Structure Setup Script (PowerShell)
#
# Generated by: claude-3.5-sonnet
# Timestamp: 2025-11-12T17:00:00Z
# Version: 1.0.0
# Policy Version: v1.0.0
# Traceability: REQ-1.3, REQ-4.2, REQ-6.4 → DESIGN-001 → TASK-1.2
# Review Status: Pending
# Risk Level: Level 2
#
# Purpose: Initialize S3 bucket folder structure and upload CloudOps templates
#
# Usage:
#   .\setup-s3-structure.ps1 -BucketName "rds-dashboard-data-123456789012-prod"
#   .\setup-s3-structure.ps1 -BucketName "rds-dashboard-data-123456789012-prod" -Region "ap-southeast-1"

param(
    [Parameter(Mandatory=$true)]
    [string]$BucketName,
    
    [Parameter(Mandatory=$false)]
    [string]$Region = "ap-southeast-1",
    
    [Parameter(Mandatory=$false)]
    [string]$TemplatesDir = "..\s3-templates",
    
    [Parameter(Mandatory=$false)]
    [switch]$SkipVerification
)

# Color output functions
function Write-Success {
    param([string]$Message)
    Write-Host "  ✓ $Message" -ForegroundColor Green
}

function Write-Error-Custom {
    param([string]$Message)
    Write-Host "  ✗ $Message" -ForegroundColor Red
}

function Write-Warning-Custom {
    param([string]$Message)
    Write-Host "  ⚠ $Message" -ForegroundColor Yellow
}

function Write-Header {
    param([string]$Message)
    Write-Host ""
    Write-Host "=" * 60 -ForegroundColor Cyan
    Write-Host $Message -ForegroundColor Cyan
    Write-Host "=" * 60 -ForegroundColor Cyan
}

# Main script
Write-Header "RDS Operations Dashboard - S3 Setup"
Write-Host "Bucket: $BucketName"
Write-Host "Region: $Region"
Write-Host "Templates: $TemplatesDir"
Write-Host "=" * 60

# Check if AWS CLI is installed
try {
    $awsVersion = aws --version 2>&1
    Write-Success "AWS CLI installed: $awsVersion"
} catch {
    Write-Error-Custom "AWS CLI not found. Please install AWS CLI first."
    Write-Host "`nInstall from: https://aws.amazon.com/cli/"
    exit 1
}

# Verify bucket exists
Write-Host "`nVerifying bucket exists..."
try {
    $bucketCheck = aws s3api head-bucket --bucket $BucketName --region $Region 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-Success "Bucket exists: $BucketName"
    } else {
        throw "Bucket not found"
    }
} catch {
    Write-Error-Custom "Bucket not found or not accessible"
    Write-Host "`nPlease ensure:"
    Write-Host "  1. The bucket exists"
    Write-Host "  2. You have appropriate IAM permissions"
    Write-Host "  3. The bucket name is correct"
    exit 1
}

# Verify bucket configuration
if (-not $SkipVerification) {
    Write-Host "`nVerifying bucket configuration..."
    
    # Check versioning
    try {
        $versioning = aws s3api get-bucket-versioning --bucket $BucketName --region $Region | ConvertFrom-Json
        if ($versioning.Status -eq "Enabled") {
            Write-Success "Versioning: Enabled"
        } else {
            Write-Warning-Custom "Versioning: Not enabled (should be enabled)"
        }
    } catch {
        Write-Warning-Custom "Could not verify versioning status"
    }
    
    # Check encryption
    try {
        $encryption = aws s3api get-bucket-encryption --bucket $BucketName --region $Region 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Success "Encryption: Enabled"
        } else {
            Write-Warning-Custom "Encryption: Not configured (should be SSE-S3)"
        }
    } catch {
        Write-Warning-Custom "Could not verify encryption status"
    }
    
    # Check lifecycle rules
    try {
        $lifecycle = aws s3api get-bucket-lifecycle-configuration --bucket $BucketName --region $Region 2>&1 | ConvertFrom-Json
        if ($lifecycle.Rules) {
            Write-Success "Lifecycle Rules: $($lifecycle.Rules.Count) configured"
            foreach ($rule in $lifecycle.Rules) {
                Write-Host "    - $($rule.ID): $($rule.Status)"
            }
        } else {
            Write-Warning-Custom "Lifecycle Rules: Not configured"
        }
    } catch {
        Write-Warning-Custom "Could not verify lifecycle rules"
    }
    
    # Check public access block
    try {
        $publicAccess = aws s3api get-public-access-block --bucket $BucketName --region $Region | ConvertFrom-Json
        $config = $publicAccess.PublicAccessBlockConfiguration
        if ($config.BlockPublicAcls -and $config.IgnorePublicAcls -and $config.BlockPublicPolicy -and $config.RestrictPublicBuckets) {
            Write-Success "Public Access: Blocked (all)"
        } else {
            Write-Warning-Custom "Public Access: Not fully blocked"
        }
    } catch {
        Write-Warning-Custom "Could not verify public access block"
    }
}

# Create folder structure
Write-Host "`nCreating folder structure..."
$folders = @(
    "historical-metrics/",
    "compliance-reports/",
    "cost-reports/",
    "cloudops-requests/",
    "templates/"
)

foreach ($folder in $folders) {
    try {
        # Create a .keep file to ensure folder exists
        $keepFile = "$folder.keep"
        $tempFile = [System.IO.Path]::GetTempFileName()
        "" | Out-File -FilePath $tempFile -Encoding ASCII
        
        aws s3api put-object `
            --bucket $BucketName `
            --key $keepFile `
            --body $tempFile `
            --server-side-encryption AES256 `
            --region $Region | Out-Null
        
        Remove-Item $tempFile
        Write-Success "Created folder: $folder"
    } catch {
        Write-Error-Custom "Failed to create folder $folder : $_"
        exit 1
    }
}

# Upload templates
Write-Host "`nUploading CloudOps templates..."
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$templatesPath = Join-Path $scriptDir $TemplatesDir | Resolve-Path

$templateFiles = @(
    "cloudops_scaling_template.md",
    "cloudops_parameter_change_template.md",
    "cloudops_maintenance_template.md"
)

foreach ($templateFile in $templateFiles) {
    $templatePath = Join-Path $templatesPath $templateFile
    
    if (-not (Test-Path $templatePath)) {
        Write-Warning-Custom "Template not found: $templatePath"
        continue
    }
    
    try {
        aws s3api put-object `
            --bucket $BucketName `
            --key "templates/$templateFile" `
            --body $templatePath `
            --content-type "text/markdown" `
            --server-side-encryption AES256 `
            --metadata "version=1.0.0,generated-by=rds-operations-dashboard" `
            --region $Region | Out-Null
        
        Write-Success "Uploaded: $templateFile"
    } catch {
        Write-Error-Custom "Failed to upload $templateFile : $_"
        exit 1
    }
}

# Success message
Write-Header "✓ S3 bucket setup completed successfully!"
Write-Host "`nNext steps:"
Write-Host "  1. Deploy Lambda functions"
Write-Host "  2. Configure EventBridge rules"
Write-Host "  3. Test discovery and health monitoring"
Write-Host "`nFolder structure created:"
Write-Host "  - historical-metrics/"
Write-Host "  - compliance-reports/"
Write-Host "  - cost-reports/"
Write-Host "  - cloudops-requests/"
Write-Host "  - templates/ (with 3 CloudOps templates)"
Write-Host ""
