#!/usr/bin/env pwsh

<#
.SYNOPSIS
Test logout flow end-to-end for critical production fixes

.DESCRIPTION
This script tests the complete logout functionality including:
- Logout URL construction
- Cognito app client configuration
- Redirect behavior
- Session clearing

Generated by: claude-3.5-sonnet
Timestamp: 2025-01-12T14:30:00Z
Version: 1.0.0
Policy Version: v1.1.0
Traceability: REQ-4.1 → TASK-2.3 → Logout Flow Testing
Review Status: Pending
Risk Level: Level 2
#>

param(
    [switch]$Verbose
)

# Configuration
$CognitoDomain = "rds-dashboard-auth-876595225096.auth.ap-southeast-1.amazoncognito.com"
$ClientId = "28e031hsul0mi91k0s6f33bs7s"
$CloudFrontDomain = "https://d2qvaswtmn22om.cloudfront.net"
$UserPoolId = "ap-southeast-1_4tyxh4qJe"

function Write-TestResult {
    param(
        [string]$Test,
        [bool]$Passed,
        [string]$Details = ""
    )
    
    $status = if ($Passed) { "✅ PASS" } else { "❌ FAIL" }
    $color = if ($Passed) { "Green" } else { "Red" }
    
    Write-Host "$status $Test" -ForegroundColor $color
    if ($Details) {
        Write-Host "    $Details" -ForegroundColor Gray
    }
}

function Test-CognitoAppClientConfig {
    Write-Host "`n🔍 Testing Cognito App Client Configuration..." -ForegroundColor Cyan
    
    try {
        $config = aws cognito-idp describe-user-pool-client --user-pool-id $UserPoolId --client-id $ClientId --query 'UserPoolClient.{CallbackURLs:CallbackURLs,LogoutURLs:LogoutURLs}' --output json | ConvertFrom-Json
        
        # Test CloudFront callback URL
        $hasCloudFrontCallback = $config.CallbackURLs -contains "$CloudFrontDomain/callback"
        Write-TestResult "CloudFront callback URL configured" $hasCloudFrontCallback "$CloudFrontDomain/callback"
        
        # Test CloudFront logout URL
        $hasCloudFrontLogout = $config.LogoutURLs -contains "$CloudFrontDomain/"
        Write-TestResult "CloudFront logout URL configured" $hasCloudFrontLogout "$CloudFrontDomain/"
        
        # Test localhost URLs
        $hasLocalhostCallback = ($config.CallbackURLs -contains "http://localhost:3000/callback") -or ($config.CallbackURLs -contains "http://localhost:5173/callback")
        Write-TestResult "Localhost callback URLs configured" $hasLocalhostCallback "Development URLs present"
        
        $hasLocalhostLogout = ($config.LogoutURLs -contains "http://localhost:3000/") -or ($config.LogoutURLs -contains "http://localhost:5173/")
        Write-TestResult "Localhost logout URLs configured" $hasLocalhostLogout "Development URLs present"
        
        return $hasCloudFrontCallback -and $hasCloudFrontLogout -and $hasLocalhostCallback -and $hasLocalhostLogout
    }
    catch {
        Write-TestResult "Cognito app client configuration" $false "Error: $($_.Exception.Message)"
        return $false
    }
}

function Test-LogoutUrlConstruction {
    Write-Host "`n🔍 Testing Logout URL Construction..." -ForegroundColor Cyan
    
    # Test CloudFront logout URL
    $cloudFrontLogoutUrl = "https://$CognitoDomain/logout?client_id=$ClientId" + [char]38 + "logout_uri=" + [System.Uri]::EscapeDataString("$CloudFrontDomain/")
    Write-Host "CloudFront logout URL: $cloudFrontLogoutUrl" -ForegroundColor Gray
    
    # Test localhost logout URL
    $localhostLogoutUrl = "https://$CognitoDomain/logout?client_id=$ClientId" + [char]38 + "logout_uri=" + [System.Uri]::EscapeDataString("http://localhost:3000/")
    Write-Host "Localhost logout URL: $localhostLogoutUrl" -ForegroundColor Gray
    
    # Validate URL format
    $hasClientId = $cloudFrontLogoutUrl -match "client_id=$ClientId"
    Write-TestResult "Logout URL contains client_id" $hasClientId "client_id=$ClientId"
    
    $hasLogoutUri = $cloudFrontLogoutUrl -match "logout_uri="
    Write-TestResult "Logout URL uses logout_uri parameter" $hasLogoutUri "Using correct parameter name"
    
    $hasEncodedUrl = $cloudFrontLogoutUrl -match [regex]::Escape([System.Uri]::EscapeDataString($CloudFrontDomain))
    Write-TestResult "Logout URL properly encoded" $hasEncodedUrl "URL encoding applied"
    
    return $hasClientId -and $hasLogoutUri -and $hasEncodedUrl
}

function Test-LogoutRedirectBehavior {
    Write-Host "`n🔍 Testing Logout Redirect Behavior..." -ForegroundColor Cyan
    
    $logoutUrl = "https://$CognitoDomain/logout?client_id=$ClientId" + [char]38 + "logout_uri=" + [System.Uri]::EscapeDataString("$CloudFrontDomain/")
    
    try {
        # Test logout endpoint response
        $response = Invoke-WebRequest -Uri $logoutUrl -Method GET -UseBasicParsing -MaximumRedirection 0 -ErrorAction SilentlyContinue
        
        if ($response.StatusCode -eq 302) {
            Write-TestResult "Logout endpoint returns redirect (302)" $true "Status: $($response.StatusCode)"
            
            $location = $response.Headers.Location
            if ($location) {
                Write-TestResult "Logout redirect has Location header" $true "Location: $location"
                
                # Check if redirect goes to expected domain
                $redirectsToCloudFront = $location -match [regex]::Escape($CloudFrontDomain)
                Write-TestResult "Logout redirects to CloudFront domain" $redirectsToCloudFront "Redirect target: $location"
                
                return $true
            } else {
                Write-TestResult "Logout redirect has Location header" $false "No Location header found"
                return $false
            }
        } else {
            Write-TestResult "Logout endpoint returns redirect (302)" $false "Status: $($response.StatusCode)"
            return $false
        }
    }
    catch {
        # Check if it's a redirect exception (which is expected)
        if ($_.Exception.Response.StatusCode -eq 302) {
            Write-TestResult "Logout endpoint returns redirect (302)" $true "Redirect response received"
            
            $location = $_.Exception.Response.Headers.Location
            if ($location) {
                Write-TestResult "Logout redirect has Location header" $true "Location: $location"
                
                $redirectsToCloudFront = $location -match [regex]::Escape($CloudFrontDomain)
                Write-TestResult "Logout redirects to CloudFront domain" $redirectsToCloudFront "Redirect target: $location"
                
                return $true
            } else {
                Write-TestResult "Logout redirect has Location header" $false "No Location header found"
                return $false
            }
        } else {
            Write-TestResult "Logout endpoint accessibility" $false "Error: $($_.Exception.Message)"
            return $false
        }
    }
}

function Test-FrontendLogoutImplementation {
    Write-Host "`n🔍 Testing Frontend Logout Implementation..." -ForegroundColor Cyan
    
    $cognitoTsPath = "frontend/src/lib/auth/cognito.ts"
    
    if (Test-Path $cognitoTsPath) {
        $content = Get-Content $cognitoTsPath -Raw
        
        # Check for logout_uri parameter usage
        $usesLogoutUri = $content -match "logout_uri="
        Write-TestResult "Frontend uses logout_uri parameter" $usesLogoutUri "Correct parameter name"
        
        # Check for proper URL encoding
        $hasUrlEncoding = $content -match "encodeURIComponent"
        Write-TestResult "Frontend properly encodes logout URL" $hasUrlEncoding "URL encoding present"
        
        # Check for logout method
        $hasLogoutMethod = $content -match "logout\(\):"
        Write-TestResult "Frontend has logout method" $hasLogoutMethod "Logout method defined"
        
        # Check for session clearing
        $clearsSession = $content -match "this\.session = null"
        Write-TestResult "Frontend clears session on logout" $clearsSession "Session cleanup present"
        
        return $usesLogoutUri -and $hasUrlEncoding -and $hasLogoutMethod -and $clearsSession
    } else {
        Write-TestResult "Frontend logout implementation" $false "File not found: $cognitoTsPath"
        return $false
    }
}
}

function Test-DashboardAccessibility {
    Write-Host "`n🔍 Testing Dashboard Accessibility..." -ForegroundColor Cyan
    
    try {
        $response = Invoke-WebRequest -Uri $CloudFrontDomain -UseBasicParsing -TimeoutSec 10
        
        $isAccessible = $response.StatusCode -eq 200
        Write-TestResult "CloudFront dashboard accessible" $isAccessible "Status: $($response.StatusCode)"
        
        # Check if it's a React app
        $isReactApp = $response.Content -match "react|React"
        Write-TestResult "Dashboard is React application" $isReactApp "React content detected"
        
        # Check for authentication elements
        $hasAuthElements = $response.Content -match "login|Login|auth|Auth"
        Write-TestResult "Dashboard has authentication elements" $hasAuthElements "Auth-related content found"
        
        return $isAccessible
    }
    catch {
        Write-TestResult "CloudFront dashboard accessibility" $false "Error: $($_.Exception.Message)"
        return $false
    }
}

# Main execution
Write-Host "🧪 Testing Logout Flow End-to-End" -ForegroundColor Yellow
Write-Host "Dashboard: $CloudFrontDomain" -ForegroundColor Gray
Write-Host "Cognito Domain: $CognitoDomain" -ForegroundColor Gray
Write-Host ""

$results = @()
$results += Test-CognitoAppClientConfig
$results += Test-LogoutUrlConstruction
$results += Test-LogoutRedirectBehavior
$results += Test-FrontendLogoutImplementation
$results += Test-DashboardAccessibility

$passedTests = ($results | Where-Object { $_ -eq $true }).Count
$totalTests = $results.Count

Write-Host "`n📊 Test Summary" -ForegroundColor Yellow
Write-Host "Passed: $passedTests/$totalTests tests" -ForegroundColor $(if ($passedTests -eq $totalTests) { "Green" } else { "Yellow" })

if ($passedTests -eq $totalTests) {
    Write-Host "`n✅ All logout flow tests passed!" -ForegroundColor Green
    Write-Host "The logout functionality should work correctly." -ForegroundColor Green
    
    Write-Host "`n🔧 Manual Testing Steps:" -ForegroundColor Cyan
    Write-Host "1. Open: $CloudFrontDomain" -ForegroundColor White
    Write-Host "2. Login with test credentials" -ForegroundColor White
    Write-Host "3. Click the logout button" -ForegroundColor White
    Write-Host "4. Verify clean redirect to login page" -ForegroundColor White
    Write-Host "5. Ensure no redirect_uri errors in browser console" -ForegroundColor White
} else {
    Write-Host "`n❌ Some logout flow tests failed!" -ForegroundColor Red
    Write-Host "Please review the failed tests above and fix the issues." -ForegroundColor Red
}

Write-Host "`n📋 Next Steps:" -ForegroundColor Yellow
Write-Host "- Perform manual testing using the steps above" -ForegroundColor White
Write-Host "- Check browser console for any JavaScript errors" -ForegroundColor White
Write-Host "- Verify session is properly cleared after logout" -ForegroundColor White
Write-Host "- Test logout from different dashboard pages" -ForegroundColor White

exit $(if ($passedTests -eq $totalTests) { 0 } else { 1 })