#!/usr/bin/env python3
"""
Script to update Lambda handlers to use structured logging.

Generated by: claude-3.5-sonnet
Timestamp: 2025-12-03T00:00:00Z
Version: 1.0.0
Policy Version: v1.0.0
Traceability: REQ-5.1 → DESIGN-5.1 → TASK-4.3
Review Status: Pending
Risk Level: Level 2
"""

import os
import re
from pathlib import Path

# Lambda handlers to update
LAMBDA_HANDLERS = [
    'rds-operations-dashboard/lambda/approval-workflow/handler.py',
    'rds-operations-dashboard/lambda/cloudops-generator/handler.py',
    'rds-operations-dashboard/lambda/compliance-checker/handler.py',
    'rds-operations-dashboard/lambda/cost-analyzer/handler.py',
    'rds-operations-dashboard/lambda/operations/handler.py',
    'rds-operations-dashboard/lambda/query-handler/handler.py',
    'rds-operations-dashboard/lambda/health-monitor/handler.py',
]

def update_handler(file_path: str):
    """Update a Lambda handler to use structured logging."""
    print(f"Updating {file_path}...")
    
    with open(file_path, 'r') as f:
        content = f.read()
    
    # Check if already updated
    if 'from shared.structured_logger import get_logger' in content:
        print(f"  ✓ Already updated")
        return
    
    # Add imports after existing shared imports
    if 'from shared import' in content:
        content = re.sub(
            r'(from shared import [^\n]+)',
            r'\1\nfrom shared.structured_logger import get_logger\nfrom shared.correlation_middleware import with_correlation_id, CorrelationContext',
            content,
            count=1
        )
    else:
        # Add imports before lambda_handler
        content = re.sub(
            r'(def lambda_handler)',
            r'from shared.structured_logger import get_logger\nfrom shared.correlation_middleware import with_correlation_id, CorrelationContext\n\n\n\1',
            content,
            count=1
        )
    
    # Add decorator to lambda_handler
    if '@with_correlation_id' not in content:
        content = re.sub(
            r'(\ndef lambda_handler\(event, context\):)',
            r'\n@with_correlation_id\1',
            content
        )
    
    # Replace logger initialization in lambda_handler
    # Pattern 1: logger = StructuredLogger('service-name')
    content = re.sub(
        r"logger = StructuredLogger\('([^']+)'\)",
        r"logger = get_logger('\1', event=event, lambda_context=context)",
        content
    )
    
    # Pattern 2: logger.set_correlation_id(...)
    content = re.sub(
        r"logger\.set_correlation_id\([^\)]+\)\n",
        "",
        content
    )
    
    # Pattern 3: correlation_id = context.aws_request_id
    content = re.sub(
        r"correlation_id = context\.aws_request_id[^\n]*\n",
        "",
        content
    )
    
    # Update requirements comment if present
    content = re.sub(
        r'(Requirements: [^\n]+)',
        r'\1, REQ-5.1 (structured logging)',
        content
    )
    
    with open(file_path, 'w') as f:
        f.write(content)
    
    print(f"  ✓ Updated successfully")

def main():
    """Main function."""
    print("Updating Lambda handlers to use structured logging...\n")
    
    for handler_path in LAMBDA_HANDLERS:
        if os.path.exists(handler_path):
            try:
                update_handler(handler_path)
            except Exception as e:
                print(f"  ✗ Error: {e}")
        else:
            print(f"  ✗ File not found: {handler_path}")
    
    print("\n✓ All handlers updated!")

if __name__ == '__main__':
    main()
