"""
CORS Helper Utility

Generated by: claude-3.5-sonnet
Timestamp: 2025-12-06T00:00:00Z
Version: 1.0.0
Policy Version: v1.0.0
Traceability: Security Fix - CORS Origin Validation
Review Status: Pending
Risk Level: Level 2

Purpose: Provide secure CORS header management for Lambda functions.
Validates origin against allowed list instead of using wildcard "*".
"""

import os
from typing import Dict, Optional


def get_cors_headers(event: Optional[Dict] = None) -> Dict[str, str]:
    """
    Get CORS headers with validated origin.
    
    Instead of using wildcard "*", this function:
    1. Reads allowed origins from environment variable
    2. Validates the request origin against the allowed list
    3. Returns appropriate CORS headers
    
    Args:
        event: Lambda event object (optional, for origin validation)
    
    Returns:
        Dict: CORS headers with validated origin
    
    Security:
        - Never uses wildcard "*" in production
        - Validates origin against allowlist
        - Falls back to first allowed origin if no event provided
    
    Environment Variables:
        ALLOWED_ORIGINS: Comma-separated list of allowed origins
                        Example: "https://dashboard.example.com,https://admin.example.com"
    """
    # Get allowed origins from environment variable
    allowed_origins_str = os.environ.get(
        'ALLOWED_ORIGINS',
        'https://dashboard.example.com'  # Default for development
    )
    
    # Parse allowed origins
    allowed_origins = [origin.strip() for origin in allowed_origins_str.split(',')]
    
    # Get request origin from event
    request_origin = None
    if event and 'headers' in event:
        # API Gateway headers are case-insensitive, check both cases
        headers = event['headers']
        request_origin = headers.get('origin') or headers.get('Origin')
    
    # Validate origin
    if request_origin and request_origin in allowed_origins:
        # Request origin is in allowed list
        allowed_origin = request_origin
    else:
        # Use first allowed origin as default
        # Note: This means requests from non-allowed origins will still get a response
        # but with a different origin header (browser will block it)
        allowed_origin = allowed_origins[0]
    
    return {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': allowed_origin,
        'Access-Control-Allow-Headers': 'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token',
        'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS',
        'Access-Control-Allow-Credentials': 'true',  # Required when not using "*"
        'Vary': 'Origin'  # Important for caching
    }


def get_simple_cors_headers(event: Optional[Dict] = None) -> Dict[str, str]:
    """
    Get simplified CORS headers (for read-only endpoints).
    
    Args:
        event: Lambda event object (optional, for origin validation)
    
    Returns:
        Dict: Simplified CORS headers with validated origin
    """
    headers = get_cors_headers(event)
    # Override methods for read-only endpoints
    headers['Access-Control-Allow-Methods'] = 'GET,OPTIONS'
    return headers


def is_preflight_request(event: Dict) -> bool:
    """
    Check if the request is a CORS preflight request.
    
    Args:
        event: Lambda event object
    
    Returns:
        bool: True if preflight request, False otherwise
    """
    http_method = event.get('httpMethod', '').upper()
    return http_method == 'OPTIONS'


def handle_preflight(event: Dict) -> Dict:
    """
    Handle CORS preflight OPTIONS request.
    
    Args:
        event: Lambda event object
    
    Returns:
        Dict: Response for preflight request
    """
    return {
        'statusCode': 200,
        'headers': get_cors_headers(event),
        'body': ''
    }


# Example usage
if __name__ == '__main__':
    import json
    
    # Test with mock event
    mock_event = {
        'headers': {
            'origin': 'https://dashboard.example.com'
        }
    }
    
    print("CORS Headers:")
    print(json.dumps(get_cors_headers(mock_event), indent=2))
    
    print("\nSimple CORS Headers:")
    print(json.dumps(get_simple_cors_headers(mock_event), indent=2))
    
    print("\nPreflight Response:")
    print(json.dumps(handle_preflight(mock_event), indent=2))

