"""
Unit Tests for Alerting Module

Generated by: claude-3.5-sonnet
Timestamp: 2025-11-12T20:30:00Z

Run with: pytest tests/test_alerting.py -v
"""

import pytest
import sys
import os

# Add parent directory to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))


def test_alerting_imports():
    """Test that alerting module can be imported."""
    try:
        from health_monitor import alerting
        assert True
    except ImportError as e:
        pytest.fail(f"Import failed: {e}")


def test_alert_severity_enum():
    """Test AlertSeverity enum."""
    from health_monitor.alerting import AlertSeverity
    
    assert AlertSeverity.CRITICAL.value == 'Critical'
    assert AlertSeverity.HIGH.value == 'High'
    assert AlertSeverity.MEDIUM.value == 'Medium'
    assert AlertSeverity.LOW.value == 'Low'


def test_threshold_rule_creation():
    """Test ThresholdRule creation."""
    from health_monitor.alerting import ThresholdRule, AlertSeverity
    
    rule = ThresholdRule(
        metric_name='CPUUtilization',
        threshold=80.0,
        comparison='gt',
        severity=AlertSeverity.HIGH,
        consecutive_violations=2,
        description='CPU above 80%'
    )
    
    assert rule.metric_name == 'CPUUtilization'
    assert rule.threshold == 80.0
    assert rule.comparison == 'gt'
    assert rule.severity == AlertSeverity.HIGH
    assert rule.consecutive_violations == 2


def test_threshold_rule_evaluate_gt():
    """Test threshold evaluation - greater than."""
    from health_monitor.alerting import ThresholdRule, AlertSeverity
    
    rule = ThresholdRule(
        metric_name='CPUUtilization',
        threshold=80.0,
        comparison='gt',
        severity=AlertSeverity.HIGH
    )
    
    # Should violate
    assert rule.evaluate(85.0) == True
    assert rule.evaluate(95.0) == True
    
    # Should not violate
    assert rule.evaluate(75.0) == False
    assert rule.evaluate(80.0) == False


def test_threshold_rule_evaluate_lt():
    """Test threshold evaluation - less than."""
    from health_monitor.alerting import ThresholdRule, AlertSeverity
    
    rule = ThresholdRule(
        metric_name='FreeStorageSpace',
        threshold=10.0,
        comparison='lt',
        severity=AlertSeverity.CRITICAL
    )
    
    # Should violate
    assert rule.evaluate(5.0) == True
    assert rule.evaluate(9.9) == True
    
    # Should not violate
    assert rule.evaluate(15.0) == False
    assert rule.evaluate(10.0) == False


def test_threshold_rule_evaluate_gte():
    """Test threshold evaluation - greater than or equal."""
    from health_monitor.alerting import ThresholdRule, AlertSeverity
    
    rule = ThresholdRule(
        metric_name='DatabaseConnections',
        threshold=90.0,
        comparison='gte',
        severity=AlertSeverity.HIGH
    )
    
    # Should violate
    assert rule.evaluate(90.0) == True
    assert rule.evaluate(95.0) == True
    
    # Should not violate
    assert rule.evaluate(85.0) == False


def test_threshold_rule_evaluate_lte():
    """Test threshold evaluation - less than or equal."""
    from health_monitor.alerting import ThresholdRule, AlertSeverity
    
    rule = ThresholdRule(
        metric_name='FreeMemory',
        threshold=20.0,
        comparison='lte',
        severity=AlertSeverity.MEDIUM
    )
    
    # Should violate
    assert rule.evaluate(20.0) == True
    assert rule.evaluate(15.0) == True
    
    # Should not violate
    assert rule.evaluate(25.0) == False


def test_default_thresholds_exist():
    """Test that default thresholds are defined."""
    from health_monitor.alerting import DEFAULT_THRESHOLDS
    
    assert len(DEFAULT_THRESHOLDS) > 0
    
    # Check for key metrics
    metric_names = [rule.metric_name for rule in DEFAULT_THRESHOLDS]
    assert 'CPUUtilization' in metric_names
    assert 'DatabaseConnections' in metric_names
    assert 'FreeStorageSpace' in metric_names
    assert 'DiskQueueDepth' in metric_names


def test_alert_manager_structure():
    """Test AlertManager class structure."""
    from health_monitor.alerting import AlertManager
    
    # Check class exists
    assert AlertManager is not None
    
    # Check required methods exist
    assert hasattr(AlertManager, 'evaluate_metrics')
    assert hasattr(AlertManager, 'store_alerts')
    assert hasattr(AlertManager, 'send_notifications')


def test_create_alert_structure():
    """Test alert creation structure."""
    from health_monitor.alerting import ThresholdRule, AlertSeverity
    
    # Create a mock instance
    instance = {
        'instance_id': 'test-instance-1',
        'account_id': '123456789012',
        'region': 'ap-southeast-1'
    }
    
    rule = ThresholdRule(
        metric_name='CPUUtilization',
        threshold=80.0,
        comparison='gt',
        severity=AlertSeverity.HIGH,
        description='CPU above 80%'
    )
    
    # Alert should have required fields
    # (This would be tested with actual AlertManager instance)
    assert rule.metric_name == 'CPUUtilization'
    assert rule.severity == AlertSeverity.HIGH


def test_notification_message_format():
    """Test notification message building."""
    # This tests the structure without needing AWS
    alert = {
        'instance_id': 'test-instance-1',
        'account_id': '123456789012',
        'region': 'ap-southeast-1',
        'metric_name': 'CPUUtilization',
        'current_value': 95.5,
        'threshold': 80.0,
        'severity': 'Critical',
        'description': 'CPU above 80%',
        'violation_count': 2
    }
    
    # Verify alert structure
    assert 'instance_id' in alert
    assert 'metric_name' in alert
    assert 'severity' in alert
    assert alert['current_value'] > alert['threshold']


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
