"""
Basic Unit Tests for RDS Dashboard

Generated by: claude-3.5-sonnet
Timestamp: 2025-11-12T19:30:00Z

Run with: pytest tests/test_basic.py -v
"""

import pytest
import sys
import os

# Add parent directory to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))


def test_imports():
    """Test that all modules can be imported."""
    try:
        from shared import aws_clients
        from shared import logger
        from shared import config
        assert True
    except ImportError as e:
        pytest.fail(f"Import failed: {e}")


def test_logger_creation():
    """Test logger can be created."""
    from shared.logger import StructuredLogger
    
    logger = StructuredLogger('test-service')
    assert logger is not None
    assert logger.service_name == 'test-service'


def test_logger_methods():
    """Test logger methods work."""
    from shared.logger import StructuredLogger
    
    logger = StructuredLogger('test-service')
    
    # These should not raise exceptions
    logger.debug('Debug message', key='value')
    logger.info('Info message', key='value')
    logger.warn('Warning message', key='value')
    logger.error('Error message', key='value')
    
    assert True


def test_sanitize_log_data():
    """Test sensitive data sanitization."""
    from shared.logger import sanitize_log_data
    
    sensitive_data = {
        'username': 'john.doe',
        'password': 'secret123',
        'api_key': 'abc123',
        'instance_id': 'i-1234567890'
    }
    
    sanitized = sanitize_log_data(sensitive_data)
    
    assert sanitized['username'] == 'john.doe'
    assert sanitized['password'] == '[REDACTED]'
    assert sanitized['api_key'] == '[REDACTED]'
    assert sanitized['instance_id'] == 'i-1234567890'


def test_config_structure():
    """Test configuration structure."""
    from shared.config import DynamoDBConfig, S3Config, CrossAccountConfig
    
    # Test DynamoDB config
    db_config = DynamoDBConfig(
        inventory_table='test-inventory',
        metrics_cache_table='test-cache',
        health_alerts_table='test-alerts',
        audit_log_table='test-audit'
    )
    
    assert db_config.inventory_table == 'test-inventory'
    
    # Test S3 config
    s3_config = S3Config(data_bucket='test-bucket')
    assert s3_config.data_bucket == 'test-bucket'
    
    # Test cross-account config
    cross_account = CrossAccountConfig(
        role_name='TestRole',
        external_id='test-id',
        target_accounts=['123456789012'],
        target_regions=['ap-southeast-1']
    )
    
    assert cross_account.role_name == 'TestRole'
    assert len(cross_account.target_accounts) == 1


def test_discovery_handler_structure():
    """Test discovery handler has required functions."""
    from discovery import handler
    
    # Check required functions exist
    assert hasattr(handler, 'lambda_handler')
    assert hasattr(handler, 'discover_all_instances')
    assert hasattr(handler, 'discover_account_instances')
    assert hasattr(handler, 'discover_region_instances')
    assert hasattr(handler, 'extract_instance_metadata')
    
    # Check functions are callable
    assert callable(handler.lambda_handler)
    assert callable(handler.discover_all_instances)


def test_health_monitor_handler_structure():
    """Test health monitor handler has required functions."""
    from health_monitor import handler
    
    # Check required functions exist
    assert hasattr(handler, 'lambda_handler')
    assert hasattr(handler, 'get_active_instances')
    assert hasattr(handler, 'monitor_all_instances')
    assert hasattr(handler, 'monitor_instance')
    assert hasattr(handler, 'get_metrics_for_instance')
    
    # Check functions are callable
    assert callable(handler.lambda_handler)
    assert callable(handler.monitor_all_instances)


def test_cache_manager_structure():
    """Test cache manager has required methods."""
    from health_monitor.cache_manager import MetricsCacheManager
    
    # Check class exists
    assert MetricsCacheManager is not None
    
    # Check required methods exist
    assert hasattr(MetricsCacheManager, 'get')
    assert hasattr(MetricsCacheManager, 'put')
    assert hasattr(MetricsCacheManager, 'get_statistics')
    assert hasattr(MetricsCacheManager, 'publish_cache_metrics')


def test_get_metrics_for_instance():
    """Test metric configuration for instances."""
    from health_monitor.handler import get_metrics_for_instance
    
    instance = {
        'instance_id': 'test-instance',
        'engine': 'postgres',
        'instance_class': 'db.t3.micro'
    }
    
    metrics = get_metrics_for_instance(instance)
    
    # Should return list of metrics
    assert isinstance(metrics, list)
    assert len(metrics) > 0
    
    # Each metric should have required fields
    for metric in metrics:
        assert 'name' in metric
        assert 'period' in metric
        assert 'stat' in metric


def test_extract_instance_metadata():
    """Test instance metadata extraction."""
    from discovery.handler import extract_instance_metadata
    
    # Mock RDS instance data
    db_instance = {
        'DBInstanceIdentifier': 'test-instance',
        'DBInstanceArn': 'arn:aws:rds:ap-southeast-1:123456789012:db:test-instance',
        'Engine': 'postgres',
        'EngineVersion': '15.4',
        'DBInstanceClass': 'db.t3.micro',
        'DBInstanceStatus': 'available',
        'AllocatedStorage': 20,
        'StorageType': 'gp3',
        'MultiAZ': False,
        'BackupRetentionPeriod': 7,
        'StorageEncrypted': True,
        'DeletionProtection': False
    }
    
    metadata = extract_instance_metadata(
        db_instance=db_instance,
        account_id='123456789012',
        region='ap-southeast-1'
    )
    
    # Verify required fields
    assert metadata['instance_id'] == 'test-instance'
    assert metadata['account_id'] == '123456789012'
    assert metadata['region'] == 'ap-southeast-1'
    assert metadata['engine'] == 'postgres'
    assert metadata['engine_version'] == '15.4'
    assert metadata['instance_class'] == 'db.t3.micro'
    assert metadata['status'] == 'available'
    assert metadata['storage_encrypted'] == True
    assert metadata['backup_retention_period'] == 7


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
